/**
 * End-to-end tests against the real HTTP surface, converting real documents
 * with the real soffice.
 *
 * These assert the wire contract the shipped Android client depends on: a
 * success is application/pdf, a failure is a non-2xx carrying the JSON
 * envelope, and a failure is never a 200.
 */
import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fsp from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import {
  buildArchiveFixture,
  buildDeclaredSizeBombFixture,
  buildEncryptedZipFixture,
  buildEntryCountBombFixture,
  buildImageFixture,
  buildIsoFixture,
  buildLegacyFixture,
  buildPptxFixture,
  buildSymlinkEscapeFixture,
  buildZipSlipFixture,
  expectJsonEnvelope,
  listWorkspaces,
  startTestServer,
  tarEntryNames,
  tarGzContainsFile,
  upload,
  waitFor,
  zipEntryNames,
  type TestServer,
} from '../../support/helpers.ts';
import {
  buildEncryptedDocxContainer,
  buildEncryptedLegacyDoc,
  buildEncryptedPdfContainer,
  buildMalformedDocx,
} from '../../support/fixtures.ts';

const execFileAsync = promisify(execFile);

const {
  buildMinimalDocx,
  buildMinimalOdg,
  buildMinimalOdp,
  buildSolidPng,
  pdfProbe,
  pdfScannedProbe,
  pdfWithType3FontProbe,
  pdfTableProbe,
  psdProbe,
  tablesProbe,
} = await import('../../../src/lib/probe-documents.ts');
const { readZipEntry } = await import('../../../src/lib/unzip.ts');
const { MAX_UPLOAD_BYTES } = await import('../../../src/config.ts');

/** A small but genuine .docx, built from real OOXML parts. */
const SAMPLE_DOCX = buildMinimalDocx([
  'Pagination fidelity check',
  'Calibri and Cambria metrics determine where every line breaks.',
  'The quick brown fox jumps over the lazy dog, repeatedly, to fill a line.',
]);

/**
 * The non-Word sources used by the matrix tests.
 *
 * These are written as literal file contents rather than built, because that is
 * what they are: CSV, text and RTF have no container to construct, and a
 * fixture that looks like the file a user would upload is easier to trust than
 * one that is generated by code nobody reads.
 */
const SAMPLE_CSV = Buffer.from('name,qty,price\nwidget,3,9.99\ngadget,12,1.5\n', 'utf8');
const SAMPLE_TXT = Buffer.from('A plain text note.\nSecond line.\n', 'utf8');
const SAMPLE_RTF = Buffer.from(
  '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 A legacy document.\\par}',
  'utf8',
);

/**
 * Big enough that a conversion takes long enough to interrupt.
 * Measured: ~850ms of soffice startup plus ~0.4ms per paragraph, so this is
 * roughly 2.5s - comfortably longer than the time it takes to notice soffice
 * running and walk away.
 */
const LARGE_DOCX = buildMinimalDocx(
  Array.from(
    { length: 8000 },
    (_, i) =>
      `Paragraph ${i}: the quick brown fox jumps over the lazy dog, again and again, filling the line so pagination is observable across many pages.`,
  ),
);

let server: TestServer;

before(async () => {
  server = await startTestServer();
});

after(async () => {
  await server.close();
});

describe('GET /health', () => {
  it('reports ok once soffice has been confirmed', async () => {
    const response = await fetch(`${server.baseUrl}/health`);
    assert.equal(response.status, 200);
    assert.match(response.headers.get('content-type') ?? '', /application\/json/);
    const body = (await response.json()) as { status: string; queue: object; mediaQueue: object };
    assert.equal(body.status, 'ok');
    assert.deepEqual(Object.keys(body.queue).sort(), ['maxConcurrent', 'maxQueued', 'queued', 'running'].sort());
    assert.deepEqual(Object.keys(body.mediaQueue).sort(), ['maxConcurrent', 'maxQueued', 'queued', 'running'].sort());
  });
});

describe('POST /convert/pdf - success', () => {
  it('converts a real .docx and returns PDF bytes', async () => {
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX);

    assert.equal(response.status, 200);
    // Constraint 1: the client checks this header and refuses anything else.
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
    assert.ok(response.body.length > 1000, 'PDF looks implausibly small');
  });

  it('accepts .docm', async () => {
    const response = await upload(server.baseUrl, 'sample.docm', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('accepts a .doc extension', async () => {
    // LibreOffice sniffs content, so OOXML written under a .doc name still
    // converts - the point here is that the extension is allowed through the
    // filter rather than rejected with 415.
    const response = await upload(server.baseUrl, 'sample.doc', SAMPLE_DOCX);
    assert.notEqual(response.status, 415);
  });

  it('picks the import filter from the filename, not the declared MIME type', async () => {
    // The client deliberately sends application/octet-stream; a hostile client
    // could send anything at all. The extension is the only thing we act on.
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, {
      mimeType: 'image/png',
    });
    assert.equal(response.status, 200);
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('ignores a path-traversal filename and keeps the upload inside its workspace', async () => {
    const response = await upload(server.baseUrl, '../../../../tmp/evil.docx', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    // Nothing was written outside the temp root: the name on disk is ours.
    assert.equal(await fsp.readdir('/tmp').then((e) => e.includes('evil.docx')), false);
  });

  it('deletes the workspace before answering', async () => {
    const before_ = await listWorkspaces();
    const response = await upload(server.baseUrl, 'cleanup.docx', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    // Cleanup happens before the response is written, so there is no race here.
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/pdf - rejections', () => {
  it('rejects an oversized upload with 413', async () => {
    const response = await upload(
      server.baseUrl,
      'big.docx',
      Buffer.alloc(MAX_UPLOAD_BYTES + 1024, 0x41),
    );
    // multer's default here would be an HTML error page; the client needs JSON.
    const error = expectJsonEnvelope(response, 413, 'E_TOO_LARGE');
    assert.equal(error.message, 'This document is too large to convert.');
  });

  it('rejects an unsupported extension with 415', async () => {
    // .exe is not in the matrix - and note that .png IS, so this test has to
    // name something genuinely outside it to stay meaningful.
    const response = await upload(server.baseUrl, 'program.exe', SAMPLE_DOCX);
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED');
    assert.match(error.message, /^This file type cannot be converted\. Supported types: /);
    // The message has to say what WOULD work, not just that this did not.
    assert.match(error.message, /\.docx/);
  });

  it('rejects a file with no extension with 415', async () => {
    const response = await upload(server.baseUrl, 'document', SAMPLE_DOCX);
    expectJsonEnvelope(response, 415, 'E_UNSUPPORTED');
  });

  it('rejects a malformed document with 500', async () => {
    const response = await upload(server.baseUrl, 'broken.docx', buildMalformedDocx());
    const error = expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
    assert.equal(
      error.message,
      'This document could not be converted. It may be damaged or in a format the converter does not support.',
    );
  });

  it('rejects an empty upload rather than returning a blank PDF', async () => {
    // LibreOffice happily opens a zero-byte file as an empty document and
    // exports a valid blank PDF, which would be a 200 carrying a document the
    // user never had.
    const response = await upload(server.baseUrl, 'empty.docx', Buffer.alloc(0));
    expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
  });

  it('rejects an encrypted .docx with 422', async () => {
    const response = await upload(server.baseUrl, 'secret.docx', buildEncryptedDocxContainer());
    const error = expectJsonEnvelope(response, 422, 'E_ENCRYPTED');
    assert.equal(error.message, 'This document is password protected.');
  });

  it('rejects an encrypted legacy .doc with 422', async () => {
    const response = await upload(server.baseUrl, 'secret.doc', buildEncryptedLegacyDoc());
    expectJsonEnvelope(response, 422, 'E_ENCRYPTED');
  });

  it('rejects a request with no file part with 400', async () => {
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, {
      fieldName: 'document',
    });
    expectJsonEnvelope(response, 400, 'E_BAD_REQUEST');
  });

  it('never returns a failure as a 200', async () => {
    const failures = [
      await upload(server.baseUrl, 'animation.gif', SAMPLE_DOCX),
      await upload(server.baseUrl, 'broken.docx', buildMalformedDocx()),
      await upload(server.baseUrl, 'empty.docx', Buffer.alloc(0)),
      await upload(server.baseUrl, 'secret.docx', buildEncryptedDocxContainer()),
    ];
    for (const response of failures) {
      assert.notEqual(response.status, 200);
      assert.ok(response.status >= 400 && response.status < 600);
      assert.match(response.contentType ?? '', /application\/json/);
    }
  });

  it('deletes the workspace after a failed conversion', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'broken.docx', buildMalformedDocx());
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('the target segment is required', () => {
  it('does not serve the bare /convert path', async () => {
    // The alias was removed deliberately. A request to it now lands on the
    // catch-all 404, whose message happens to be the right thing to say to
    // someone on an out-of-date client: "please update the app".
    const form = new FormData();
    form.append('file', new Blob([new Uint8Array(SAMPLE_DOCX)]), 'sample.docx');
    const response = await fetch(`${server.baseUrl}/convert`, { method: 'POST', body: form });

    assert.equal(response.status, 404);
    const body = (await response.json()) as { error: { code: string; message: string } };
    assert.equal(body.error.code, 'E_BAD_REQUEST');
    assert.equal(
      body.error.message,
      'The converter is not available at this address. Please update the app and try again.',
    );
  });

  it('serves the same conversion at /convert/pdf', async () => {
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, { target: 'pdf' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });
});

describe('download filenames', () => {
  it('keeps the upload name and swaps the extension', async () => {
    const response = await upload(server.baseUrl, 'Quarterly report.docx', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    assert.match(response.contentDisposition ?? '', /filename="Quarterly report\.pdf"/);
  });

  it('names a raster archive after the deck it came from', async () => {
    // The ENTRIES stay slide-1.png, slide-2.png; only the archive is named
    // after the upload, so unzipping gives predictable page names either way.
    const response = await upload(server.baseUrl, 'my deck.odp', buildMinimalOdp(['a', 'b']), {
      target: 'png',
    });
    assert.equal(response.status, 200);
    assert.match(response.contentDisposition ?? '', /filename="my deck\.zip"/);
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.png', 'slide-2.png']);
  });

  it('keeps a non-ASCII name intact through the whole stack', async () => {
    // The end-to-end version of the decode test: this goes through the real
    // multipart parser, so if multer's treatment of the filename ever changes
    // (or is fixed upstream), the unit test still passes while this one does
    // not - which is the one that describes what a user experiences.
    const name = 'KVADRAT KÖKLƏR 8-Cİ SİNİF (ARZU ƏLƏDDİN QIZI 051-641-88-34)';
    const response = await upload(server.baseUrl, `${name}.docx`, SAMPLE_DOCX);

    assert.equal(response.status, 200);
    const disposition = response.contentDisposition ?? '';

    // The starred form is what current clients read, and it must carry the
    // exact name the user typed. Compared as a substring rather than matched as
    // a pattern: the name contains parentheses, which `encodeURIComponent`
    // leaves alone and a regex would read as grouping.
    const expected = `filename*=UTF-8''${encodeURIComponent(name)}.pdf`;
    assert.ok(
      disposition.includes(expected),
      `expected the header to carry ${expected}, got ${disposition}`,
    );
    // And nothing left over from the latin1 misreading: no C1 controls, and
    // no `Ã`/`Ä` pile-up.
    assert.doesNotMatch(disposition, /[\u0080-\u009f]/, 'a C1 control reached the header');
    assert.doesNotMatch(disposition, /Ã|Ä|Æ/, 'the latin1 misreading was passed on');
  });

  it('does not let a hostile filename reach the header', async () => {
    // The name is attacker-controlled and this value is a response header, so
    // a CRLF in it would be a header injection. Sanitised, not escaped.
    const response = await upload(server.baseUrl, '../../etc/evil\r\nX-Loop: 1.docx', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    const disposition = response.contentDisposition ?? '';
    assert.doesNotMatch(disposition, /[\r\n]/, 'a newline reached the header');
    assert.match(disposition, /filename="evilX-Loop: 1\.pdf"/);
  });
});
