/**
 * End-to-end tests against the real HTTP surface, converting real documents
 * with the real soffice.
 *
 * These assert the wire contract the shipped Android client depends on: a
 * success is application/pdf, a failure is a non-2xx carrying the JSON
 * envelope, and a failure is never a 200.
 */
import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fsp from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import {
  buildArchiveFixture,
  buildDeclaredSizeBombFixture,
  buildEncryptedZipFixture,
  buildEntryCountBombFixture,
  buildImageFixture,
  buildIsoFixture,
  buildLegacyFixture,
  buildPptxFixture,
  buildSymlinkEscapeFixture,
  buildZipSlipFixture,
  expectJsonEnvelope,
  listWorkspaces,
  startTestServer,
  tarEntryNames,
  tarGzContainsFile,
  upload,
  waitFor,
  zipEntryNames,
  type TestServer,
} from '../../support/helpers.ts';
import {
  buildEncryptedDocxContainer,
  buildEncryptedLegacyDoc,
  buildEncryptedPdfContainer,
  buildMalformedDocx,
} from '../../support/fixtures.ts';

const execFileAsync = promisify(execFile);

const {
  buildMinimalDocx,
  buildMinimalOdg,
  buildMinimalOdp,
  buildSolidPng,
  pdfProbe,
  pdfScannedProbe,
  pdfWithType3FontProbe,
  pdfTableProbe,
  psdProbe,
  tablesProbe,
} = await import('../../../src/lib/probe-documents.ts');
const { readZipEntry } = await import('../../../src/lib/unzip.ts');
const { MAX_UPLOAD_BYTES } = await import('../../../src/config.ts');

/** A small but genuine .docx, built from real OOXML parts. */
const SAMPLE_DOCX = buildMinimalDocx([
  'Pagination fidelity check',
  'Calibri and Cambria metrics determine where every line breaks.',
  'The quick brown fox jumps over the lazy dog, repeatedly, to fill a line.',
]);

/**
 * The non-Word sources used by the matrix tests.
 *
 * These are written as literal file contents rather than built, because that is
 * what they are: CSV, text and RTF have no container to construct, and a
 * fixture that looks like the file a user would upload is easier to trust than
 * one that is generated by code nobody reads.
 */
const SAMPLE_CSV = Buffer.from('name,qty,price\nwidget,3,9.99\ngadget,12,1.5\n', 'utf8');
const SAMPLE_TXT = Buffer.from('A plain text note.\nSecond line.\n', 'utf8');
const SAMPLE_RTF = Buffer.from(
  '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 A legacy document.\\par}',
  'utf8',
);

/**
 * Big enough that a conversion takes long enough to interrupt.
 * Measured: ~850ms of soffice startup plus ~0.4ms per paragraph, so this is
 * roughly 2.5s - comfortably longer than the time it takes to notice soffice
 * running and walk away.
 */
const LARGE_DOCX = buildMinimalDocx(
  Array.from(
    { length: 8000 },
    (_, i) =>
      `Paragraph ${i}: the quick brown fox jumps over the lazy dog, again and again, filling the line so pagination is observable across many pages.`,
  ),
);

let server: TestServer;

before(async () => {
  server = await startTestServer();
});

after(async () => {
  await server.close();
});

describe('GET /formats', () => {
  it('describes the matrix the server actually implements', async () => {
    const response = await fetch(`${server.baseUrl}/formats`);
    assert.equal(response.status, 200);

    const body = (await response.json()) as {
      targets: Array<{ id: string; mediaType: string; multiple: boolean }>;
      sources: Array<{ extension: string; family: string; targets: string[] }>;
    };

    const targetIds = body.targets.map((target) => target.id);
    assert.ok(targetIds.includes('pdf'));
    assert.ok(targetIds.includes('png'));

    // The targets whose answer is an archive. The raster ones are one image per
    // page; `layers` is one image per layer of a PSD. Both are always archives,
    // so this is a fact about the target and not about the document.
    const MULTIPLE = ['png', 'jpg', 'layers'];
    for (const target of body.targets) {
      assert.equal(target.multiple, MULTIPLE.includes(target.id), target.id);
    }

    const docx = body.sources.find((source) => source.extension === '.docx');
    // `tables` is the one Word target LibreOffice does not produce: it is our
    // own extractor reading the document's own package.
    assert.deepEqual(docx?.targets, ['pdf', 'odt', 'txt', 'html', 'rtf', 'epub', 'tables']);

    // Every target a source claims has to exist in the target list, or the
    // document is advertising something the server would 404 on.
    for (const source of body.sources) {
      assert.equal(source.extension, source.extension.toLowerCase());
      for (const target of source.targets) {
        assert.ok(targetIds.includes(target), `${source.extension} claims unknown ${target}`);
      }
    }
  });
});

describe('cancellation', () => {
  it('kills the running soffice when the client disconnects', async () => {
    const controller = new AbortController();
    const form = new FormData();
    form.append('files', new Blob([new Uint8Array(LARGE_DOCX)]), 'large.docx');

    const request = fetch(`${server.baseUrl}/convert/pdf`, {
      method: 'POST',
      body: form,
      signal: controller.signal,
    }).catch(() => undefined); // The abort rejects this; that is the point.

    // Wait for soffice to actually be running, so this test cannot pass
    // vacuously by aborting before any work started.
    const started = await waitFor(async () => (await sofficeForWorkspaces()).length > 0, 30_000);
    assert.ok(started, 'soffice never started; the fixture may be too small to interrupt');

    const abortedAt = Date.now();
    controller.abort();
    await request;

    // The workspace goes away...
    const cleaned = await waitFor(async () => (await listWorkspaces()).length === 0, 20_000);
    assert.ok(cleaned, 'workspace was not cleaned up after the client disconnected');

    // ...and so does the process, rather than burning CPU until the timeout.
    const killed = await waitFor(async () => (await sofficeForWorkspaces()).length === 0, 20_000);
    assert.ok(killed, `soffice still running: ${(await sofficeForWorkspaces()).join(' | ')}`);

    // Proving it was killed rather than merely finishing: an 8000-paragraph
    // document needs ~2.5s, and we walked away about 100ms in. If this were
    // natural completion it could not possibly be this quick.
    const killedAfterMs = Date.now() - abortedAt;
    assert.ok(
      killedAfterMs < 1500,
      `soffice took ${killedAfterMs}ms to disappear after the abort - it looks like it ran to completion instead of being killed`,
    );
  });
});

async function sofficeForWorkspaces(): Promise<string[]> {
  const { TEMP_ROOT } = await import('../../support/helpers.ts');
  try {
    const { stdout } = await execFileAsync('ps', ['-eo', 'args'], { maxBuffer: 8 * 1024 * 1024 });
    return stdout
      .split('\n')
      .filter((line) => line.includes(TEMP_ROOT) && line.includes('soffice'))
      .map((line) => line.trim());
  } catch {
    return [];
  }
}
