/**
 * End-to-end tests against the real HTTP surface, converting real documents
 * with the real soffice.
 *
 * These assert the wire contract the shipped Android client depends on: a
 * success is application/pdf, a failure is a non-2xx carrying the JSON
 * envelope, and a failure is never a 200.
 */
import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fsp from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import {
  buildArchiveFixture,
  buildDeclaredSizeBombFixture,
  buildEncryptedZipFixture,
  buildEntryCountBombFixture,
  buildImageFixture,
  buildIsoFixture,
  buildLegacyFixture,
  buildPptxFixture,
  buildSymlinkEscapeFixture,
  buildZipSlipFixture,
  expectJsonEnvelope,
  listWorkspaces,
  startTestServer,
  tarEntryNames,
  tarGzContainsFile,
  upload,
  waitFor,
  zipEntryNames,
  type TestServer,
} from '../../support/helpers.ts';
import {
  buildEncryptedDocxContainer,
  buildEncryptedLegacyDoc,
  buildEncryptedPdfContainer,
  buildMalformedDocx,
} from '../../support/fixtures.ts';

const execFileAsync = promisify(execFile);

const {
  buildMinimalDocx,
  buildMinimalOdg,
  buildMinimalOdp,
  buildSolidPng,
  pdfProbe,
  pdfScannedProbe,
  pdfWithType3FontProbe,
  pdfTableProbe,
  psdProbe,
  tablesProbe,
} = await import('../../../src/lib/probe-documents.ts');
const { readZipEntry } = await import('../../../src/lib/unzip.ts');
const { MAX_UPLOAD_BYTES } = await import('../../../src/config.ts');

/** A small but genuine .docx, built from real OOXML parts. */
const SAMPLE_DOCX = buildMinimalDocx([
  'Pagination fidelity check',
  'Calibri and Cambria metrics determine where every line breaks.',
  'The quick brown fox jumps over the lazy dog, repeatedly, to fill a line.',
]);

/**
 * The non-Word sources used by the matrix tests.
 *
 * These are written as literal file contents rather than built, because that is
 * what they are: CSV, text and RTF have no container to construct, and a
 * fixture that looks like the file a user would upload is easier to trust than
 * one that is generated by code nobody reads.
 */
const SAMPLE_CSV = Buffer.from('name,qty,price\nwidget,3,9.99\ngadget,12,1.5\n', 'utf8');
const SAMPLE_TXT = Buffer.from('A plain text note.\nSecond line.\n', 'utf8');
const SAMPLE_RTF = Buffer.from(
  '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 A legacy document.\\par}',
  'utf8',
);

/**
 * Big enough that a conversion takes long enough to interrupt.
 * Measured: ~850ms of soffice startup plus ~0.4ms per paragraph, so this is
 * roughly 2.5s - comfortably longer than the time it takes to notice soffice
 * running and walk away.
 */
const LARGE_DOCX = buildMinimalDocx(
  Array.from(
    { length: 8000 },
    (_, i) =>
      `Paragraph ${i}: the quick brown fox jumps over the lazy dog, again and again, filling the line so pagination is observable across many pages.`,
  ),
);

let server: TestServer;

before(async () => {
  server = await startTestServer();
});

after(async () => {
  await server.close();
});

describe('POST /convert/<target> - image transcode engine (ffmpeg)', () => {
  it('converts a real PNG to WEBP, a real RIFF/WEBP container', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const response = await upload(server.baseUrl, 'photo.png', png, { target: 'webp' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/webp');
    assert.equal(response.body.subarray(0, 4).toString('ascii'), 'RIFF');
    assert.equal(response.body.subarray(8, 12).toString('ascii'), 'WEBP');
  });

  it('converts a real PNG to BMP', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const response = await upload(server.baseUrl, 'photo.png', png, { target: 'bmp' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/bmp');
    assert.equal(response.body.subarray(0, 2).toString('ascii'), 'BM');
  });

  it('converts a real PNG to GIF', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const response = await upload(server.baseUrl, 'photo.png', png, { target: 'gif' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/gif');
    assert.equal(response.body.subarray(0, 6).toString('ascii'), 'GIF89a');
  });

  it('converts a real JPEG to TIFF', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const jpeg = await buildImageFixture(png, 'jpg');
    const response = await upload(server.baseUrl, 'photo.jpg', jpeg, { target: 'tiff' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/tiff');
    // Little-endian TIFF magic: "II" followed by 42.
    assert.equal(response.body.subarray(0, 4).toString('latin1'), 'II*\0');
  });

  it('reads a real WEBP source and converts it to AVIF', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const webp = await buildImageFixture(png, 'webp');
    const response = await upload(server.baseUrl, 'photo.webp', webp, { target: 'avif' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/avif');
  });

  it('reads a real GIF source (decoded as a tiny video) and still produces one still image', async () => {
    // The whole reason `-frames:v 1 -update 1` is mandatory rather than
    // cosmetic - see ffmpeg.engine.ts's own header comment: without it, a
    // GIF source (which ffmpeg decodes as a one-frame video, not a still
    // image) trips "Cannot write more than one file with the same name" and
    // the conversion fails outright, verified by hand before this flag was
    // added.
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const gif = await buildImageFixture(png, 'gif');
    const response = await upload(server.baseUrl, 'photo.gif', gif, { target: 'bmp' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/bmp');
  });

  it('refuses an image over 256x256 asking for ICO, honestly rather than silently downscaling', async () => {
    // A real format limitation, verified by hand: ffmpeg refuses with
    // "Unsupported dimensions ... (dimensions cannot exceed 256x256)" for
    // anything larger, and this service does not auto-resize to make a
    // request succeed for any other target either.
    const png = buildSolidPng(300, 300, [10, 90, 200]);
    const response = await upload(server.baseUrl, 'big.png', png, { target: 'ico' });
    assert.equal(response.status, 500);
    expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
  });

  it('a small image converts to ICO successfully', async () => {
    const png = buildSolidPng(32, 32, [10, 90, 200]);
    const response = await upload(server.baseUrl, 'icon.png', png, { target: 'ico' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/x-icon');
  });

  it('does not offer an image source the png/jpg targets - those ids mean paginated raster output', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const bmp = await buildImageFixture(png, 'bmp');

    const asPng = await upload(server.baseUrl, 'photo.bmp', bmp, { target: 'png' });
    assert.equal(asPng.status, 415);
    expectJsonEnvelope(asPng, 415, 'E_UNSUPPORTED_TARGET');

    const asJpg = await upload(server.baseUrl, 'photo.bmp', bmp, { target: 'jpg' });
    assert.equal(asJpg.status, 415);
    expectJsonEnvelope(asJpg, 415, 'E_UNSUPPORTED_TARGET');
  });

  it('converts a real PNG to a real single-file JPEG via jpg-image', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const response = await upload(server.baseUrl, 'photo.png', png, { target: 'jpg-image' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/jpeg');
    // JPEG magic: FF D8 FF.
    assert.equal(response.body.subarray(0, 3).toString('hex'), 'ffd8ff');
  });

  it('converts a real JPEG to a real single-file PNG via png-image', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const jpeg = await buildImageFixture(png, 'jpg');
    const response = await upload(server.baseUrl, 'photo.jpg', jpeg, { target: 'png-image' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'image/png');
    assert.equal(response.body.subarray(1, 4).toString('ascii'), 'PNG');
  });

  it('does not offer .png the jpg-image target as png-image (no self-conversion), but .jpeg can reach jpg-image', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const selfPng = await upload(server.baseUrl, 'photo.png', png, { target: 'png-image' });
    assert.equal(selfPng.status, 415);
    expectJsonEnvelope(selfPng, 415, 'E_UNSUPPORTED_TARGET');

    const jpeg = await buildImageFixture(png, 'jpg');
    const jpegToJpgImage = await upload(server.baseUrl, 'photo.jpeg', jpeg, { target: 'jpg-image' });
    assert.equal(jpegToJpgImage.status, 200);
    assert.equal(jpegToJpgImage.contentType, 'image/jpeg');
  });

  it('still reaches pdf from a plain image upload, unaffected by the new transcode targets', async () => {
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    const response = await upload(server.baseUrl, 'photo.png', png, { target: 'pdf' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
  });

  it('deletes the workspace after a transcode conversion', async () => {
    const before_ = await listWorkspaces();
    const png = buildSolidPng(16, 16, [10, 90, 200]);
    await upload(server.baseUrl, 'photo.png', png, { target: 'webp' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/<target> - subtitle transcode engine (ffmpeg)', () => {
  const srtFixture = Buffer.from(
    '1\n00:00:01,000 --> 00:00:03,000\nHello world\n\n2\n00:00:04,000 --> 00:00:06,000\nSecond line\n',
    'utf8',
  );
  const vttFixture = Buffer.from(
    'WEBVTT\n\n00:00:01.000 --> 00:00:03.000\nHello world\n\n00:00:04.000 --> 00:00:06.000\nSecond line\n',
    'utf8',
  );
  const assFixture = Buffer.from(
    '[Script Info]\nScriptType: v4.00+\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:01.00,0:00:03.00,Default,,0,0,0,,Hello world\nDialogue: 0,0:00:04.00,0:00:06.00,Default,,0,0,0,,Second line\n',
    'utf8',
  );

  it('converts a real SRT to a real WEBVTT', async () => {
    const response = await upload(server.baseUrl, 'captions.srt', srtFixture, { target: 'vtt' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'text/vtt');
    assert.match(response.body.toString('utf8'), /^WEBVTT/);
    assert.match(response.body.toString('utf8'), /Hello world/);
  });

  it('converts a real WEBVTT to a real SRT', async () => {
    const response = await upload(server.baseUrl, 'captions.vtt', vttFixture, { target: 'srt' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/x-subrip');
    assert.match(response.body.toString('utf8'), /-->/);
    assert.match(response.body.toString('utf8'), /Second line/);
  });

  it('converts a real ASS to a real SRT and a real VTT', async () => {
    const toSrt = await upload(server.baseUrl, 'captions.ass', assFixture, { target: 'srt' });
    assert.equal(toSrt.status, 200);
    assert.equal(toSrt.contentType, 'application/x-subrip');
    assert.match(toSrt.body.toString('utf8'), /Hello world/);

    const toVtt = await upload(server.baseUrl, 'captions.ass', assFixture, { target: 'vtt' });
    assert.equal(toVtt.status, 200);
    assert.equal(toVtt.contentType, 'text/vtt');
  });

  it('converts a real SRT to a real SSA', async () => {
    const response = await upload(server.baseUrl, 'captions.srt', srtFixture, { target: 'ssa' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'text/x-ssa');
    assert.match(response.body.toString('utf8'), /\[Script Info\]/);
  });

  it('reads a real SSA source back into SRT', async () => {
    const ssaResponse = await upload(server.baseUrl, 'captions.srt', srtFixture, { target: 'ssa' });
    const response = await upload(server.baseUrl, 'captions.ssa', ssaResponse.body, { target: 'srt' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/x-subrip');
    assert.match(response.body.toString('utf8'), /Hello world/);
  });

  it('does not offer a subtitle source its own format as a target', async () => {
    const response = await upload(server.baseUrl, 'captions.srt', srtFixture, { target: 'srt' });
    assert.equal(response.status, 415);
    expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
  });

  it('rejects .sub and .mpl uploads as unsupported extensions', async () => {
    // MicroDVD (.sub) and MPL2 (.mpl) were deliberately left out of the
    // matrix - see formats.ts's SUBTITLE_TRANSCODE_TARGETS comment: this
    // ffmpeg build has no muxer for either, so there is no way to produce
    // one, and MicroDVD additionally needs a per-pair -framerate flag this
    // engine never sends.
    const subResponse = await upload(server.baseUrl, 'captions.sub', Buffer.from('{1}{75}hi'), {
      target: 'srt',
    });
    assert.equal(subResponse.status, 415);
    expectJsonEnvelope(subResponse, 415, 'E_UNSUPPORTED');

    const mplResponse = await upload(server.baseUrl, 'captions.mpl', Buffer.from('[0][50]hi'), {
      target: 'srt',
    });
    assert.equal(mplResponse.status, 415);
    expectJsonEnvelope(mplResponse, 415, 'E_UNSUPPORTED');
  });
});

describe('POST /convert/<target> - data engine (JSON/YAML/CSV/TSV/JSONL)', () => {
  const csvFixture = Buffer.from('name,age\nAda,36\nGrace,85\n', 'utf8');
  const jsonFixture = Buffer.from(
    JSON.stringify([
      { name: 'Ada', age: 36 },
      { name: 'Grace', age: 85 },
    ]),
    'utf8',
  );
  const yamlFixture = Buffer.from('- name: Ada\n  age: 36\n- name: Grace\n  age: 85\n', 'utf8');
  const jsonlFixture = Buffer.from(
    '{"name":"Ada","age":36}\n{"name":"Grace","age":85}\n',
    'utf8',
  );

  it('converts a real CSV to real JSON, preserving every row', async () => {
    const response = await upload(server.baseUrl, 'people.csv', csvFixture, { target: 'json' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/json; charset=utf-8');
    const parsed = JSON.parse(response.body.toString('utf8'));
    assert.deepEqual(parsed, [
      { name: 'Ada', age: '36' },
      { name: 'Grace', age: '85' },
    ]);
  });

  it('converts a real JSON array of records to real CSV', async () => {
    const response = await upload(server.baseUrl, 'people.json', jsonFixture, { target: 'csv' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'text/csv; charset=utf-8');
    assert.equal(response.body.toString('utf8'), 'name,age\r\nAda,36\r\nGrace,85\r\n');
  });

  it('converts a real YAML document to real TSV', async () => {
    const response = await upload(server.baseUrl, 'people.yaml', yamlFixture, { target: 'tsv' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'text/tab-separated-values; charset=utf-8');
    assert.equal(response.body.toString('utf8'), 'name\tage\r\nAda\t36\r\nGrace\t85\r\n');
  });

  it('converts a real JSONL stream to real YAML', async () => {
    const response = await upload(server.baseUrl, 'people.jsonl', jsonlFixture, { target: 'yaml' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/yaml; charset=utf-8');
    const text = response.body.toString('utf8');
    assert.match(text, /name: Ada/);
    assert.match(text, /age: 36/);
  });

  it('converts real CSV with a quoted, comma-containing field to JSON and back to CSV', async () => {
    const withComma = Buffer.from('city,note\nParis,"hello, world"\n', 'utf8');
    const toJson = await upload(server.baseUrl, 'notes.csv', withComma, { target: 'json' });
    assert.equal(toJson.status, 200);
    assert.deepEqual(JSON.parse(toJson.body.toString('utf8')), [{ city: 'Paris', note: 'hello, world' }]);

    const backToCsv = await upload(server.baseUrl, 'notes.json', toJson.body, { target: 'csv' });
    assert.equal(backToCsv.status, 200);
    assert.equal(backToCsv.body.toString('utf8'), 'city,note\r\nParis,"hello, world"\r\n');
  });

  it('refuses a non-tabular JSON document asking for CSV, with a specific reason', async () => {
    const singleObject = Buffer.from(JSON.stringify({ name: 'Ada', age: 36 }), 'utf8');
    const response = await upload(server.baseUrl, 'person.json', singleObject, { target: 'csv' });
    assert.equal(response.status, 422);
    expectJsonEnvelope(response, 422, 'E_NOT_TABULAR');
  });

  it('refuses malformed JSON with a conversion failure, not a crash', async () => {
    const broken = Buffer.from('{not valid json', 'utf8');
    const response = await upload(server.baseUrl, 'broken.json', broken, { target: 'yaml' });
    assert.equal(response.status, 500);
    expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
  });

  it('does not offer a data source its own format as a target', async () => {
    const response = await upload(server.baseUrl, 'people.json', jsonFixture, { target: 'json' });
    assert.equal(response.status, 415);
    expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
  });

  it('still reaches xlsx/ods/pdf from a .csv upload through the ordinary LibreOffice route', async () => {
    const response = await upload(server.baseUrl, 'people.csv', csvFixture, { target: 'xlsx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );
  });
});
