/**
 * End-to-end tests against the real HTTP surface, converting real documents
 * with the real soffice.
 *
 * These assert the wire contract the shipped Android client depends on: a
 * success is application/pdf, a failure is a non-2xx carrying the JSON
 * envelope, and a failure is never a 200.
 */
import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fsp from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import {
  buildArchiveFixture,
  buildDeclaredSizeBombFixture,
  buildEncryptedZipFixture,
  buildEntryCountBombFixture,
  buildImageFixture,
  buildIsoFixture,
  buildLegacyFixture,
  buildPptxFixture,
  buildSymlinkEscapeFixture,
  buildZipSlipFixture,
  expectJsonEnvelope,
  listWorkspaces,
  startTestServer,
  tarEntryNames,
  tarGzContainsFile,
  upload,
  waitFor,
  zipEntryNames,
  type TestServer,
} from '../../support/helpers.ts';
import {
  buildEncryptedDocxContainer,
  buildEncryptedLegacyDoc,
  buildEncryptedPdfContainer,
  buildMalformedDocx,
} from '../../support/fixtures.ts';

const execFileAsync = promisify(execFile);

const {
  buildMinimalDocx,
  buildMinimalOdg,
  buildMinimalOdp,
  buildSolidPng,
  pdfProbe,
  pdfScannedProbe,
  pdfWithType3FontProbe,
  pdfTableProbe,
  psdProbe,
  tablesProbe,
} = await import('../../../src/lib/probe-documents.ts');
const { readZipEntry } = await import('../../../src/lib/unzip.ts');
const { MAX_UPLOAD_BYTES } = await import('../../../src/config.ts');

/** A small but genuine .docx, built from real OOXML parts. */
const SAMPLE_DOCX = buildMinimalDocx([
  'Pagination fidelity check',
  'Calibri and Cambria metrics determine where every line breaks.',
  'The quick brown fox jumps over the lazy dog, repeatedly, to fill a line.',
]);

/**
 * The non-Word sources used by the matrix tests.
 *
 * These are written as literal file contents rather than built, because that is
 * what they are: CSV, text and RTF have no container to construct, and a
 * fixture that looks like the file a user would upload is easier to trust than
 * one that is generated by code nobody reads.
 */
const SAMPLE_CSV = Buffer.from('name,qty,price\nwidget,3,9.99\ngadget,12,1.5\n', 'utf8');
const SAMPLE_TXT = Buffer.from('A plain text note.\nSecond line.\n', 'utf8');
const SAMPLE_RTF = Buffer.from(
  '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 A legacy document.\\par}',
  'utf8',
);

/**
 * Big enough that a conversion takes long enough to interrupt.
 * Measured: ~850ms of soffice startup plus ~0.4ms per paragraph, so this is
 * roughly 2.5s - comfortably longer than the time it takes to notice soffice
 * running and walk away.
 */
const LARGE_DOCX = buildMinimalDocx(
  Array.from(
    { length: 8000 },
    (_, i) =>
      `Paragraph ${i}: the quick brown fox jumps over the lazy dog, again and again, filling the line so pagination is observable across many pages.`,
  ),
);

let server: TestServer;

before(async () => {
  server = await startTestServer();
});

after(async () => {
  await server.close();
});

describe('POST /convert/<target> - markup sources (pandoc)', () => {
  const SAMPLE_MD = Buffer.from(
    '# Heading\n\nSome **bold** text and a list:\n\n- one\n- two\n\n| a | b |\n|---|---|\n| 1 | 2 |\n',
    'utf8',
  );
  const SAMPLE_RST = Buffer.from('Heading\n=======\n\nSome **bold** text.\n\n- one\n- two\n', 'utf8');
  const SAMPLE_ORG = Buffer.from('* Heading\n\nSome *bold* text.\n', 'utf8');
  const SAMPLE_IPYNB = Buffer.from(
    JSON.stringify({
      cells: [
        { cell_type: 'markdown', metadata: {}, source: ['# Heading\n', 'text'] },
        { cell_type: 'code', execution_count: null, metadata: {}, outputs: [], source: ["print('hi')"] },
      ],
      metadata: { kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' } },
      nbformat: 4,
      nbformat_minor: 5,
    }),
    'utf8',
  );

  it('converts Markdown to a real DOCX', async () => {
    const response = await upload(server.baseUrl, 'note.md', SAMPLE_MD, { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'docx is not a zip package');
  });

  it('converts reStructuredText to HTML', async () => {
    const response = await upload(server.baseUrl, 'note.rst', SAMPLE_RST, { target: 'html' });
    assert.equal(response.status, 200);
    assert.match(response.contentType ?? '', /^text\/html/);
    assert.match(response.body.toString('utf8'), /Heading/);
  });

  it('converts an Org file to ODT and to plain text', async () => {
    const odt = await upload(server.baseUrl, 'note.org', SAMPLE_ORG, { target: 'odt' });
    assert.equal(odt.status, 200);
    assert.equal(odt.contentType, 'application/vnd.oasis.opendocument.text');

    const txt = await upload(server.baseUrl, 'note.org', SAMPLE_ORG, { target: 'txt' });
    assert.equal(txt.status, 200);
    assert.match(txt.contentType ?? '', /^text\/plain/);
    assert.match(txt.body.toString('utf8'), /Heading/);
  });

  it('converts a Jupyter notebook to RTF', async () => {
    const response = await upload(server.baseUrl, 'note.ipynb', SAMPLE_IPYNB, { target: 'rtf' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/rtf');
  });

  it("converts reStructuredText to GitHub-flavoured Markdown, via pandoc's own gfm writer", async () => {
    const response = await upload(server.baseUrl, 'note.rst', SAMPLE_RST, { target: 'markdown' });
    assert.equal(response.status, 200);
    assert.match(response.contentType ?? '', /^text\/markdown/);
    assert.match(response.body.toString('utf8'), /\*\*bold\*\*/);
  });

  it('does not offer .md the markdown target - a Markdown file has nothing to become', async () => {
    const response = await upload(server.baseUrl, 'note.md', SAMPLE_MD, { target: 'markdown' });
    assert.equal(response.status, 415);
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.doesNotMatch(error.message, /Markdown/);
  });

  it('rejects an unsupported target for a markup source, listing what it can become', async () => {
    const response = await upload(server.baseUrl, 'note.md', SAMPLE_MD, { target: 'xlsx' });
    assert.equal(response.status, 415);
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.match(error.message, /DOCX/);
  });

  it('deletes the workspace after a pandoc conversion', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'note.md', SAMPLE_MD, { target: 'docx' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/<target> - archive engine (7z)', () => {
  it('converts a real ZIP to a real TAR, preserving the file tree', async () => {
    const zip = await buildArchiveFixture('zip', { 'a.txt': 'hello', 'sub/b.txt': 'nested' });
    const response = await upload(server.baseUrl, 'archive.zip', zip, { target: 'tar' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/x-tar');
    const names = await tarEntryNames(response.body);
    assert.equal(names.sort().join(','), 'a.txt,sub/,sub/b.txt');
  });

  it('converts a real ZIP to a real CBZ, preserving the page files', async () => {
    const zip = await buildArchiveFixture('zip', { '001.jpg': 'page one', '002.jpg': 'page two' });
    const response = await upload(server.baseUrl, 'comic.zip', zip, { target: 'cbz' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/vnd.comicbook+zip');
    assert.deepEqual(zipEntryNames(response.body).sort(), ['001.jpg', '002.jpg']);
  });

  it('reads a real CBZ back as a ZIP', async () => {
    const cbz = await buildArchiveFixture('zip', { '001.jpg': 'page one' });
    const response = await upload(server.baseUrl, 'comic.cbz', cbz, { target: 'zip' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body), ['001.jpg']);
  });

  it('converts a real TAR to a real ZIP', async () => {
    const tar = await buildArchiveFixture('tar', { 'one.txt': 'one', 'dir/two.txt': 'two' });
    const response = await upload(server.baseUrl, 'archive.tar', tar, { target: 'zip' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body).sort(), ['dir/two.txt', 'one.txt']);
  });

  it('converts a real 7z to tar.gz and tar.bz2, both readable by real tar', async () => {
    const sevenZip = await buildArchiveFixture('7z', { 'note.txt': 'seven zip contents' });

    const targz = await upload(server.baseUrl, 'archive.7z', sevenZip, { target: 'tar.gz' });
    assert.equal(targz.status, 200);
    assert.equal(targz.contentType, 'application/gzip');
    assert.equal(await tarGzContainsFile(targz.body, 'note.txt'), true);

    const tarbz2 = await upload(server.baseUrl, 'archive.7z', sevenZip, { target: 'tar.bz2' });
    assert.equal(tarbz2.status, 200);
    assert.equal(tarbz2.contentType, 'application/x-bzip2');
  });

  it('converts a real ISO 9660 image to a ZIP', async () => {
    const iso = await buildIsoFixture({ 'readme.txt': 'iso contents' });
    const response = await upload(server.baseUrl, 'disk.iso', iso, { target: 'zip' });
    assert.equal(response.status, 200);
    assert.deepEqual(zipEntryNames(response.body), ['readme.txt']);
  });

  it('reads a bare .gz (no tar layer) as a single-file archive', async () => {
    const dir = await fsp.mkdtemp(join(tmpdir(), 'converter-plaingz-'));
    const filePath = join(dir, 'solo.txt');
    await fsp.writeFile(filePath, 'just one file');
    await execFileAsync('gzip', ['-k', filePath]);
    const bytes = await fsp.readFile(join(dir, 'solo.txt.gz'));
    await fsp.rm(dir, { recursive: true, force: true }).catch(() => {});

    const response = await upload(server.baseUrl, 'solo.gz', bytes, { target: 'zip' });
    assert.equal(response.status, 200);
    assert.deepEqual(zipEntryNames(response.body), ['solo.txt']);
  });

  it('does not offer .zip the zip target - a ZIP file has nothing to become', async () => {
    const zip = await buildArchiveFixture('zip', { 'a.txt': 'hello' });
    const response = await upload(server.baseUrl, 'archive.zip', zip, { target: 'zip' });
    assert.equal(response.status, 415);
    expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
  });

  it('rejects an unknown archive extension as unsupported', async () => {
    // `.rar` is a supported source (read-only - 7z can extract it but never
    // write it), so the ordinary 415 for an extension outside the matrix is
    // proved with one that is genuinely not in it: a client that tries anyway
    // gets the 415 envelope, not a 500 from some half-wired code path.
    const response = await upload(server.baseUrl, 'archive.arj', Buffer.from('`\xea\x00\x00'), {
      target: 'zip',
    });
    assert.equal(response.status, 415);
    expectJsonEnvelope(response, 415, 'E_UNSUPPORTED');
  });

  describe('malicious archives are refused, not silently sanitised', () => {
    it('refuses a zip-slip attempt and never writes outside the workspace', async () => {
      const canary = '/tmp/converter-archive-slip-canary';
      await fsp.rm(canary, { recursive: true, force: true }).catch(() => {});

      const evil = await buildZipSlipFixture();
      const response = await upload(server.baseUrl, 'evil.zip', evil, { target: 'tar' });

      // Either the pipeline refused outright, or (7z's own sanitisation)
      // it succeeded but landed everything inside the extraction directory -
      // what must NEVER happen is the canary file appearing outside it.
      const canaryExists = await fsp
        .access(canary)
        .then(() => true)
        .catch(() => false);
      assert.equal(canaryExists, false, 'zip-slip entry escaped the workspace');
      await fsp.rm(canary, { recursive: true, force: true }).catch(() => {});

      if (response.status !== 200) {
        expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
      }
    });

    it('refuses an archive containing a symlink', async () => {
      const evil = await buildSymlinkEscapeFixture();
      const response = await upload(server.baseUrl, 'evil.zip', evil, { target: 'tar' });
      assert.equal(response.status, 500);
      expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
    });

    it('refuses an archive with more entries than the cap', async () => {
      const { MAX_ARCHIVE_ENTRIES } = await import('../../../src/config.ts');
      const evil = await buildEntryCountBombFixture(MAX_ARCHIVE_ENTRIES + 1);
      const response = await upload(server.baseUrl, 'evil.zip', evil, { target: 'tar' });
      assert.equal(response.status, 500);
      expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
    });

    it('refuses an archive whose declared size is a decompression bomb', async () => {
      const { MAX_ARCHIVE_UNCOMPRESSED_BYTES } = await import('../../../src/config.ts');
      const evil = await buildDeclaredSizeBombFixture(MAX_ARCHIVE_UNCOMPRESSED_BYTES + 1024 * 1024);
      const response = await upload(server.baseUrl, 'evil.zip', evil, { target: 'tar' });
      assert.equal(response.status, 500);
      expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
    });

    it('refuses a password-protected archive as encrypted, not as a generic failure', async () => {
      const encrypted = await buildEncryptedZipFixture('Secret123');
      const response = await upload(server.baseUrl, 'protected.zip', encrypted, { target: 'tar' });
      assert.equal(response.status, 422);
      expectJsonEnvelope(response, 422, 'E_ENCRYPTED');
    });
  });

  it('deletes the workspace after an archive conversion', async () => {
    const before_ = await listWorkspaces();
    const zip = await buildArchiveFixture('zip', { 'a.txt': 'hello' });
    await upload(server.baseUrl, 'archive.zip', zip, { target: 'tar' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});
