/**
 * End-to-end tests against the real HTTP surface, converting real documents
 * with the real soffice.
 *
 * These assert the wire contract the shipped Android client depends on: a
 * success is application/pdf, a failure is a non-2xx carrying the JSON
 * envelope, and a failure is never a 200.
 */
import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fsp from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import {
  buildArchiveFixture,
  buildDeclaredSizeBombFixture,
  buildEncryptedZipFixture,
  buildEntryCountBombFixture,
  buildImageFixture,
  buildIsoFixture,
  buildLegacyFixture,
  buildPptxFixture,
  buildSymlinkEscapeFixture,
  buildZipSlipFixture,
  expectJsonEnvelope,
  listWorkspaces,
  startTestServer,
  tarEntryNames,
  tarGzContainsFile,
  upload,
  waitFor,
  zipEntryNames,
  type TestServer,
} from '../../support/helpers.ts';
import {
  buildEncryptedDocxContainer,
  buildEncryptedLegacyDoc,
  buildEncryptedPdfContainer,
  buildMalformedDocx,
} from '../../support/fixtures.ts';

const execFileAsync = promisify(execFile);

const {
  buildMinimalDocx,
  buildMinimalOdg,
  buildMinimalOdp,
  buildSolidPng,
  pdfProbe,
  pdfScannedProbe,
  pdfWithType3FontProbe,
  pdfTableProbe,
  psdProbe,
  tablesProbe,
} = await import('../../../src/lib/probe-documents.ts');
const { readZipEntry } = await import('../../../src/lib/unzip.ts');
const { MAX_UPLOAD_BYTES } = await import('../../../src/config.ts');

/** A small but genuine .docx, built from real OOXML parts. */
const SAMPLE_DOCX = buildMinimalDocx([
  'Pagination fidelity check',
  'Calibri and Cambria metrics determine where every line breaks.',
  'The quick brown fox jumps over the lazy dog, repeatedly, to fill a line.',
]);

/**
 * The non-Word sources used by the matrix tests.
 *
 * These are written as literal file contents rather than built, because that is
 * what they are: CSV, text and RTF have no container to construct, and a
 * fixture that looks like the file a user would upload is easier to trust than
 * one that is generated by code nobody reads.
 */
const SAMPLE_CSV = Buffer.from('name,qty,price\nwidget,3,9.99\ngadget,12,1.5\n', 'utf8');
const SAMPLE_TXT = Buffer.from('A plain text note.\nSecond line.\n', 'utf8');
const SAMPLE_RTF = Buffer.from(
  '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 A legacy document.\\par}',
  'utf8',
);

/**
 * Big enough that a conversion takes long enough to interrupt.
 * Measured: ~850ms of soffice startup plus ~0.4ms per paragraph, so this is
 * roughly 2.5s - comfortably longer than the time it takes to notice soffice
 * running and walk away.
 */
const LARGE_DOCX = buildMinimalDocx(
  Array.from(
    { length: 8000 },
    (_, i) =>
      `Paragraph ${i}: the quick brown fox jumps over the lazy dog, again and again, filling the line so pagination is observable across many pages.`,
  ),
);

let server: TestServer;

before(async () => {
  server = await startTestServer();
});

after(async () => {
  await server.close();
});

describe('POST /convert/<target> - the universal matrix', () => {
  it('converts a CSV to a real XLSX', async () => {
    const response = await upload(server.baseUrl, 'sheet.csv', SAMPLE_CSV, { target: 'xlsx' });

    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );
    // An xlsx is a ZIP package.
    assert.equal(response.body.readUInt32LE(0), 0x04034b50);
  });

  it('converts a CSV to PDF', async () => {
    const response = await upload(server.baseUrl, 'sheet.csv', SAMPLE_CSV, { target: 'pdf' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('converts a plain text file to DOCX', async () => {
    const response = await upload(server.baseUrl, 'notes.txt', SAMPLE_TXT, { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'docx is not a zip package');
  });

  it('converts an RTF to ODT', async () => {
    const response = await upload(server.baseUrl, 'legacy.rtf', SAMPLE_RTF, { target: 'odt' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/vnd.oasis.opendocument.text');
  });

  it('converts an image to PDF', async () => {
    const response = await upload(server.baseUrl, 'photo.png', buildSolidPng(16, 16, [10, 90, 200]));
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('converts a Word document to plain text and EPUB', async () => {
    const text = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, { target: 'txt' });
    assert.equal(text.status, 200);
    assert.match(text.contentType ?? '', /^text\/plain/);
    assert.match(text.body.toString('utf8'), /Pagination fidelity check/);

    const epub = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, { target: 'epub' });
    assert.equal(epub.status, 200);
    assert.equal(epub.contentType, 'application/epub+zip');
    assert.equal(epub.body.readUInt32LE(0), 0x04034b50, 'epub is not a zip package');
  });

  it('converts a two-slide deck to one PNG per slide, as an archive', async () => {
    // The whole reason the raster pipeline exists: LibreOffice's own image
    // export writes only the first slide, so if this ever returns a single
    // image the two-step path has been broken or bypassed.
    const response = await upload(server.baseUrl, 'deck.pptx', await buildPptxFixture(['one', 'two']), {
      target: 'png',
    });

    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.png', 'slide-2.png']);
  });

  it('rasterises a LibreOffice-native deck too', async () => {
    // .odp and .pptx are the same kind of document, so the image targets are
    // offered from both. This uses the hand-built ODP rather than the generated
    // PPTX, so it exercises the raster pipeline with no fixture dependency at
    // all - if the two ever diverge, the absence of a gap here is the point.
    const response = await upload(server.baseUrl, 'deck.odp', buildMinimalOdp(['one', 'two']), {
      target: 'png',
    });

    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.png', 'slide-2.png']);
  });

  it('converts a deck to ODP', async () => {
    const response = await upload(server.baseUrl, 'deck.pptx', await buildPptxFixture(['one']), {
      target: 'odp',
    });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/vnd.oasis.opendocument.presentation');
  });

  it('answers JPG requests with an archive too, whatever the page count', async () => {
    // A single-slide deck still answers with a zip: the content type must not
    // depend on how many slides the upload happened to have, or every client
    // has to sniff what it received.
    const response = await upload(server.baseUrl, 'one.pptx', await buildPptxFixture(['only']), {
      target: 'jpg',
    });

    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.jpg']);
  });

  it('rejects a target the source cannot become, listing what it can', async () => {
    // A .docx is a document; there is no sensible way to make it a slide deck.
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, { target: 'png' });

    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.equal(
      error.message,
      'A .docx file can be converted to: PDF, ODT, TXT, HTML, RTF, EPUB, XLSX (tables).',
    );
  });

  it('rejects an unknown target with 404, without reading the upload', async () => {
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, {
      target: 'banana',
    });

    const error = expectJsonEnvelope(response, 404, 'E_UNKNOWN_TARGET');
    // It has to name the real options - this is the only place a client can
    // discover them from an error.
    assert.match(error.message, /PDF/);
    assert.match(error.message, /XLSX/);
  });

  it('deletes the workspace after a matrix conversion', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'sheet.csv', SAMPLE_CSV, { target: 'xlsx' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/<target> - legacy/variant Office extensions', () => {
  // Each fixture is a real file in its format, generated once by running
  // soffice against an already-verified probe - see `buildLegacyFixture`.
  // This is the ground-truth check the matrix entries in formats.ts claim to
  // have passed: a matrix-shape test proves the table is consistent with
  // itself, not that soffice actually reads and writes these extensions.

  it('converts a Word template (.dot) to PDF', async () => {
    const dot = await buildLegacyFixture(SAMPLE_DOCX, '.docx', '.dot', 'MS Word 97 Vorlage');
    const response = await upload(server.baseUrl, 'template.dot', dot, { target: 'pdf' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('converts a Word template (.dotx) to HTML', async () => {
    const dotx = await buildLegacyFixture(
      SAMPLE_DOCX,
      '.docx',
      '.dotx',
      'MS Word 2007 XML Template',
    );
    const response = await upload(server.baseUrl, 'template.dotx', dotx, { target: 'html' });
    assert.equal(response.status, 200);
    assert.match(response.contentType ?? '', /^text\/html/);
  });

  it('converts a legacy Excel workbook (.xls) to ODS', async () => {
    const xls = await buildLegacyFixture(SAMPLE_CSV, '.csv', '.xls', 'MS Excel 97');
    const response = await upload(server.baseUrl, 'sheet.xls', xls, { target: 'ods' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/vnd.oasis.opendocument.spreadsheet');
  });

  it('converts a macro-enabled Excel workbook (.xlsm) to CSV', async () => {
    const xlsm = await buildLegacyFixture(SAMPLE_CSV, '.csv', '.xlsm', 'Calc MS Excel 2007 XML');
    const response = await upload(server.baseUrl, 'sheet.xlsm', xlsm, { target: 'csv' });
    assert.equal(response.status, 200);
    assert.match(response.contentType ?? '', /^text\/csv/);
  });

  it('converts a legacy PowerPoint deck (.ppt) to a real PNG per slide', async () => {
    const pptx = await buildPptxFixture(['one', 'two']);
    const ppt = await buildLegacyFixture(pptx, '.pptx', '.ppt', 'MS PowerPoint 97');
    const response = await upload(server.baseUrl, 'deck.ppt', ppt, { target: 'png' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.png', 'slide-2.png']);
  });

  it('converts a PowerPoint show (.ppsx) to PDF', async () => {
    const pptx = await buildPptxFixture(['one']);
    const ppsx = await buildLegacyFixture(
      pptx,
      '.pptx',
      '.ppsx',
      'Impress Office Open XML AutoPlay',
    );
    const response = await upload(server.baseUrl, 'deck.ppsx', ppsx, { target: 'pdf' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
  });

  it('converts a PowerPoint template (.pot) to ODP', async () => {
    const pptx = await buildPptxFixture(['one']);
    const pot = await buildLegacyFixture(pptx, '.pptx', '.pot', 'MS PowerPoint 97 Vorlage');
    const response = await upload(server.baseUrl, 'deck.pot', pot, { target: 'odp' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/vnd.oasis.opendocument.presentation');
  });

  it('converts an OpenDocument drawing (.odg) to PDF', async () => {
    const response = await upload(server.baseUrl, 'drawing.odg', buildMinimalOdg('drawing probe'), {
      target: 'pdf',
    });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
  });

  it('upgrades a legacy .doc to a real .docx', async () => {
    const doc = await buildLegacyFixture(SAMPLE_DOCX, '.docx', '.doc', 'MS Word 97');
    const response = await upload(server.baseUrl, 'letter.doc', doc, { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'docx is not a zip package');
  });

  it('upgrades a legacy .xls to a real .xlsx', async () => {
    const xls = await buildLegacyFixture(SAMPLE_CSV, '.csv', '.xls', 'MS Excel 97');
    const response = await upload(server.baseUrl, 'sheet.xls', xls, { target: 'xlsx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'xlsx is not a zip package');
  });

  it('upgrades a legacy .ppt to a real .pptx', async () => {
    const pptx = await buildPptxFixture(['one']);
    const ppt = await buildLegacyFixture(pptx, '.pptx', '.ppt', 'MS PowerPoint 97');
    const response = await upload(server.baseUrl, 'deck.ppt', ppt, { target: 'pptx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'pptx is not a zip package');
  });

  it('rejects an unsupported target for a legacy extension, listing what it can become', async () => {
    const dot = await buildLegacyFixture(SAMPLE_DOCX, '.docx', '.dot', 'MS Word 97 Vorlage');
    const response = await upload(server.baseUrl, 'template.dot', dot, { target: 'tables' });
    assert.equal(response.status, 415);
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.match(error.message, /PDF/);
  });
});

describe('POST /convert/<target> - rounding out the per-family exports', () => {
  // Every pair here uses a filter that was already proven to work for some
  // OTHER source in the same family (see formats.ts's own comments on each
  // of these sources) - these tests are the real-file proof that the
  // filter behaves identically for the source that had been left off.

  it('converts an ODT to TXT, HTML, RTF and EPUB', async () => {
    const odt = await buildLegacyFixture(SAMPLE_DOCX, '.docx', '.odt', 'writer8');

    const txt = await upload(server.baseUrl, 'letter.odt', odt, { target: 'txt' });
    assert.equal(txt.status, 200);
    assert.match(txt.contentType ?? '', /^text\/plain/);

    const html = await upload(server.baseUrl, 'letter.odt', odt, { target: 'html' });
    assert.equal(html.status, 200);
    assert.match(html.contentType ?? '', /^text\/html/);

    const rtf = await upload(server.baseUrl, 'letter.odt', odt, { target: 'rtf' });
    assert.equal(rtf.status, 200);
    assert.equal(rtf.contentType, 'application/rtf');

    const epub = await upload(server.baseUrl, 'letter.odt', odt, { target: 'epub' });
    assert.equal(epub.status, 200);
    assert.equal(epub.contentType, 'application/epub+zip');
  });

  it('converts an ODS to HTML and CSV', async () => {
    const ods = await buildLegacyFixture(SAMPLE_CSV, '.csv', '.ods', 'calc8');

    const html = await upload(server.baseUrl, 'sheet.ods', ods, { target: 'html' });
    assert.equal(html.status, 200);
    assert.match(html.contentType ?? '', /^text\/html/);

    const csv = await upload(server.baseUrl, 'sheet.ods', ods, { target: 'csv' });
    assert.equal(csv.status, 200);
    assert.match(csv.contentType ?? '', /^text\/csv/);
    assert.match(csv.body.toString('utf8'), /widget/);
  });

  it('converts a CSV to HTML', async () => {
    const response = await upload(server.baseUrl, 'sheet.csv', SAMPLE_CSV, { target: 'html' });
    assert.equal(response.status, 200);
    assert.match(response.contentType ?? '', /^text\/html/);
  });

  it('converts a plain text file to HTML, RTF and EPUB', async () => {
    const html = await upload(server.baseUrl, 'notes.txt', SAMPLE_TXT, { target: 'html' });
    assert.equal(html.status, 200);
    assert.match(html.contentType ?? '', /^text\/html/);

    const rtf = await upload(server.baseUrl, 'notes.txt', SAMPLE_TXT, { target: 'rtf' });
    assert.equal(rtf.status, 200);
    assert.equal(rtf.contentType, 'application/rtf');

    const epub = await upload(server.baseUrl, 'notes.txt', SAMPLE_TXT, { target: 'epub' });
    assert.equal(epub.status, 200);
    assert.equal(epub.contentType, 'application/epub+zip');
  });

  it('converts an HTML file to TXT, RTF and EPUB', async () => {
    const html = Buffer.from('<html><body><p>A web page.</p></body></html>', 'utf8');

    const txt = await upload(server.baseUrl, 'page.html', html, { target: 'txt' });
    assert.equal(txt.status, 200);
    assert.match(txt.contentType ?? '', /^text\/plain/);

    const rtf = await upload(server.baseUrl, 'page.html', html, { target: 'rtf' });
    assert.equal(rtf.status, 200);
    assert.equal(rtf.contentType, 'application/rtf');

    const epub = await upload(server.baseUrl, 'page.html', html, { target: 'epub' });
    assert.equal(epub.status, 200);
    assert.equal(epub.contentType, 'application/epub+zip');
  });

  it('converts an RTF to TXT, HTML and EPUB', async () => {
    const txt = await upload(server.baseUrl, 'legacy.rtf', SAMPLE_RTF, { target: 'txt' });
    assert.equal(txt.status, 200);
    assert.match(txt.contentType ?? '', /^text\/plain/);

    const html = await upload(server.baseUrl, 'legacy.rtf', SAMPLE_RTF, { target: 'html' });
    assert.equal(html.status, 200);
    assert.match(html.contentType ?? '', /^text\/html/);

    const epub = await upload(server.baseUrl, 'legacy.rtf', SAMPLE_RTF, { target: 'epub' });
    assert.equal(epub.status, 200);
    assert.equal(epub.contentType, 'application/epub+zip');
  });
});
