/**
 * End-to-end tests against the real HTTP surface, converting real documents
 * with the real soffice.
 *
 * These assert the wire contract the shipped Android client depends on: a
 * success is application/pdf, a failure is a non-2xx carrying the JSON
 * envelope, and a failure is never a 200.
 */
import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fsp from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import {
  buildArchiveFixture,
  buildDeclaredSizeBombFixture,
  buildEncryptedZipFixture,
  buildEntryCountBombFixture,
  buildImageFixture,
  buildIsoFixture,
  buildLegacyFixture,
  buildPptxFixture,
  buildSymlinkEscapeFixture,
  buildZipSlipFixture,
  expectJsonEnvelope,
  listWorkspaces,
  startTestServer,
  tarEntryNames,
  tarGzContainsFile,
  upload,
  waitFor,
  zipEntryNames,
  type TestServer,
} from '../../support/helpers.ts';
import {
  buildEncryptedDocxContainer,
  buildEncryptedLegacyDoc,
  buildEncryptedPdfContainer,
  buildMalformedDocx,
} from '../../support/fixtures.ts';

const execFileAsync = promisify(execFile);

const {
  buildMinimalDocx,
  buildMinimalOdg,
  buildMinimalOdp,
  buildSolidPng,
  pdfProbe,
  pdfScannedProbe,
  pdfWithType3FontProbe,
  pdfTableProbe,
  psdProbe,
  tablesProbe,
} = await import('../../../src/lib/probe-documents.ts');
const { readZipEntry } = await import('../../../src/lib/unzip.ts');
const { MAX_UPLOAD_BYTES } = await import('../../../src/config.ts');

/** A small but genuine .docx, built from real OOXML parts. */
const SAMPLE_DOCX = buildMinimalDocx([
  'Pagination fidelity check',
  'Calibri and Cambria metrics determine where every line breaks.',
  'The quick brown fox jumps over the lazy dog, repeatedly, to fill a line.',
]);

/**
 * The non-Word sources used by the matrix tests.
 *
 * These are written as literal file contents rather than built, because that is
 * what they are: CSV, text and RTF have no container to construct, and a
 * fixture that looks like the file a user would upload is easier to trust than
 * one that is generated by code nobody reads.
 */
const SAMPLE_CSV = Buffer.from('name,qty,price\nwidget,3,9.99\ngadget,12,1.5\n', 'utf8');
const SAMPLE_TXT = Buffer.from('A plain text note.\nSecond line.\n', 'utf8');
const SAMPLE_RTF = Buffer.from(
  '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 A legacy document.\\par}',
  'utf8',
);

/**
 * Big enough that a conversion takes long enough to interrupt.
 * Measured: ~850ms of soffice startup plus ~0.4ms per paragraph, so this is
 * roughly 2.5s - comfortably longer than the time it takes to notice soffice
 * running and walk away.
 */
const LARGE_DOCX = buildMinimalDocx(
  Array.from(
    { length: 8000 },
    (_, i) =>
      `Paragraph ${i}: the quick brown fox jumps over the lazy dog, again and again, filling the line so pagination is observable across many pages.`,
  ),
);

let server: TestServer;

before(async () => {
  server = await startTestServer();
});

after(async () => {
  await server.close();
});

describe('POST /convert/<target> - PDF sources', () => {
  /**
   * `pdfa`/`png`/`jpg` are direct/raster LibreOffice targets - a PDF is
   * always opened as a Draw document, and these are Draw's own export
   * filters. `docx`/`pptx`/`xlsx` reach no LibreOffice filter at all from a
   * PDF - confirmed by actually running `soffice --convert-to docx/pptx/xlsx`
   * against a real PDF and watching every one fail with "no export filter
   * found" - so a PDF reaches those same three ids through `pdf_engine.py`
   * instead (`engineFrom` in formats.ts). The id is the same one a `.doc`
   * upload reaches through soffice; only the engine behind it differs.
   */
  const TWO_PAGE_PDF = pdfProbe();

  it('re-exports as PDF/A through Draw', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'pdfa' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.ok(response.body.subarray(0, 5).equals(Buffer.from('%PDF-', 'latin1')));
    // PDF/A-1b declares its conformance in the XMP metadata soffice embeds.
    assert.ok(response.body.includes(Buffer.from('pdfaid')), 'not tagged as PDF/A');
  });

  it('rasterises every page, skipping the render-to-PDF step', async () => {
    // The probe has two pages, which is the point: one image each proves the
    // source was rasterised directly rather than silently dropped to one
    // page the way LibreOffice's own image export would.
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'png' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body).sort(), ['slide-1.png', 'slide-2.png']);
  });

  it('reconstructs an editable DOCX with pdf_engine.py', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'not a ZIP-based package');
    const document = readZipEntry(response.body, 'word/document.xml', 4 * 1024 * 1024);
    assert.equal(document.kind, 'found');
    const xml = document.kind === 'found' ? document.data.toString('utf8') : '';
    for (const text of ['Converter warm-up', 'Second page']) {
      assert.ok(xml.includes(text), `"${text}" did not survive the reconstruction`);
    }
  });

  it('falls back to a full-page image for a Type3-font PDF, instead of a corrupted reconstruction', async () => {
    // Regression test for a real failure: pdf2docx duplicated and overlapped
    // every line of a Type3-font PDF (confirmed against the actual file that
    // exposed this), and no pdf2docx setting changed that - so
    // pdf_engine.py detects the trigger and answers with a full-page image
    // instead. This is the one DOCX case where a page IMAGE, not
    // reconstructed text, is the correct and expected output.
    const response = await upload(server.baseUrl, 'doc.pdf', pdfWithType3FontProbe(), { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'not a ZIP-based package');
    assert.deepEqual(
      zipEntryNames(response.body).filter((name) => /^word\/media\//.test(name)),
      ['word/media/image1.png'],
      'expected exactly one full-page image, not a reconstructed text layout',
    );
  });

  it('still produces a valid DOCX for a PDF with no extractable text (a scan), ocr defaulting on', async () => {
    // Not an assertion about Tesseract's own accuracy - that is not something
    // a unit test should pin to - only that a PDF `_pdf_has_no_extractable_
    // text` flags for OCR still converts successfully end to end, whether or
    // not this host actually has tesseract installed (pdf_engine.py degrades
    // to a plain, non-OCR conversion rather than failing if it does not -
    // see its own `convert_to_docx` docstring).
    const response = await upload(server.baseUrl, 'scan.pdf', pdfScannedProbe(), { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'not a ZIP-based package');
  });

  it('accepts ocr=false and still produces a valid DOCX', async () => {
    const response = await upload(server.baseUrl, 'scan.pdf', pdfScannedProbe(), {
      target: 'docx',
      fields: { ocr: 'false' },
    });
    assert.equal(response.status, 200);
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'not a ZIP-based package');
  });

  it('rejects a malformed ocr field', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', pdfProbe(), {
      target: 'docx',
      fields: { ocr: 'maybe' },
    });
    const body = JSON.parse(response.body.toString('utf8')) as { error: { code: string; message: string } };
    assert.equal(response.status, 400);
    assert.equal(body.error.code, 'E_INVALID_FIELD');
    assert.equal(body.error.message, 'The "ocr" field must be "true" or "false".');
  });

  it('builds one slide per page, each a full-page image', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'pptx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'not a ZIP-based package');
    assert.deepEqual(
      zipEntryNames(response.body)
        .filter((name) => /^ppt\/slides\/slide\d+\.xml$/.test(name))
        .sort(),
      ['ppt/slides/slide1.xml', 'ppt/slides/slide2.xml'],
    );
  });

  it('extracts a ruled table into a workbook', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', pdfTableProbe(), { target: 'xlsx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );
    const sheet = readZipEntry(response.body, 'xl/worksheets/sheet1.xml', 1024 * 1024);
    assert.equal(sheet.kind, 'found');
    const xml = sheet.kind === 'found' ? sheet.data.toString('utf8') : '';
    for (const value of ['A1', 'B1', 'A2', 'B2']) {
      assert.ok(xml.includes(value), `"${value}" did not survive the table extraction`);
    }
  });

  it('answers E_NO_TABLES for a PDF with no ruled table', async () => {
    // The PDF-source twin of the same case for a Word document: the document
    // opened and was read successfully, and simply has nothing to extract.
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'xlsx' });
    const error = expectJsonEnvelope(response, 422, 'E_NO_TABLES');
    assert.equal(error.message, 'This document does not contain any tables.');
  });

  it('reconstructs Markdown with pdf_engine.py, keeping both pages\' text', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'markdown' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'text/markdown; charset=utf-8');
    const markdown = response.body.toString('utf8');
    assert.match(markdown, /Converter warm-up/);
    assert.match(markdown, /Second page/);
  });

  it('renders a ruled table as a GFM table in the Markdown output', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', pdfTableProbe(), { target: 'markdown' });
    assert.equal(response.status, 200);
    const markdown = response.body.toString('utf8');
    // A GFM table: a header row, a `---` separator row, and the cell values -
    // the same values `extracts a ruled table into a workbook` (above)
    // checks survived the xlsx route, here checked against the text route.
    assert.match(markdown, /\|.*---.*\|/);
    for (const value of ['A1', 'B1', 'A2', 'B2']) {
      assert.ok(markdown.includes(value), `"${value}" did not survive the Markdown table`);
    }
  });

  it('offers the same docx/pptx/xlsx ids a .doc upload would, not lookalikes', async () => {
    // There is no separate "from PDF" id to fall out of step with: a PDF
    // lists exactly `docx`/`pptx`/`xlsx` among the formats it can become,
    // the same ids GET /formats advertises for every other source.
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'odt' });
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.match(
      error.message,
      /A \.pdf file can be converted to: PDF\/A, PNG, JPG, SVG, EMF, WMF, EPS, DOCX, PPTX, XLSX, Markdown\./,
    );
  });

  it('names the download after the upload, with the target extension', async () => {
    const response = await upload(server.baseUrl, 'Contract.pdf', TWO_PAGE_PDF, { target: 'docx' });
    assert.equal(response.status, 200);
    assert.match(response.contentDisposition ?? '', /filename="Contract\.docx"/);
  });

  it('deletes the workspace after a PDF-engine conversion', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'docx' });
    assert.deepEqual(await listWorkspaces(), before_);
  });

  it('rejects an encrypted PDF with 422 rather than a generic failure', async () => {
    // Without the PDF branch in isPasswordProtected, this would reach
    // pdf_engine.py (or soffice, for pdfa/png/jpg) and come back as
    // E_CONVERT_FAILED - technically true but the wrong explanation, exactly
    // the failure this check exists to avoid for OOXML and legacy Word.
    const response = await upload(server.baseUrl, 'secret.pdf', buildEncryptedPdfContainer(), {
      target: 'docx',
    });
    const error = expectJsonEnvelope(response, 422, 'E_ENCRYPTED');
    assert.equal(error.message, 'This document is password protected.');
  });
});
