/**
 * End-to-end tests against the real HTTP surface, converting real documents
 * with the real soffice.
 *
 * These assert the wire contract the shipped Android client depends on: a
 * success is application/pdf, a failure is a non-2xx carrying the JSON
 * envelope, and a failure is never a 200.
 */
import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fsp from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import {
  buildArchiveFixture,
  buildDeclaredSizeBombFixture,
  buildEncryptedZipFixture,
  buildEntryCountBombFixture,
  buildImageFixture,
  buildIsoFixture,
  buildLegacyFixture,
  buildPptxFixture,
  buildSymlinkEscapeFixture,
  buildZipSlipFixture,
  expectJsonEnvelope,
  listWorkspaces,
  startTestServer,
  tarEntryNames,
  tarGzContainsFile,
  upload,
  waitFor,
  zipEntryNames,
  type TestServer,
} from '../../support/helpers.ts';
import {
  buildEncryptedDocxContainer,
  buildEncryptedLegacyDoc,
  buildEncryptedPdfContainer,
  buildMalformedDocx,
} from '../../support/fixtures.ts';

const execFileAsync = promisify(execFile);

const {
  buildMinimalDocx,
  buildMinimalOdg,
  buildMinimalOdp,
  buildSolidPng,
  pdfProbe,
  pdfScannedProbe,
  pdfWithType3FontProbe,
  pdfTableProbe,
  psdProbe,
  tablesProbe,
} = await import('../../../src/lib/probe-documents.ts');
const { readZipEntry } = await import('../../../src/lib/unzip.ts');
const { MAX_UPLOAD_BYTES } = await import('../../../src/config.ts');

/** A small but genuine .docx, built from real OOXML parts. */
const SAMPLE_DOCX = buildMinimalDocx([
  'Pagination fidelity check',
  'Calibri and Cambria metrics determine where every line breaks.',
  'The quick brown fox jumps over the lazy dog, repeatedly, to fill a line.',
]);

/**
 * The non-Word sources used by the matrix tests.
 *
 * These are written as literal file contents rather than built, because that is
 * what they are: CSV, text and RTF have no container to construct, and a
 * fixture that looks like the file a user would upload is easier to trust than
 * one that is generated by code nobody reads.
 */
const SAMPLE_CSV = Buffer.from('name,qty,price\nwidget,3,9.99\ngadget,12,1.5\n', 'utf8');
const SAMPLE_TXT = Buffer.from('A plain text note.\nSecond line.\n', 'utf8');
const SAMPLE_RTF = Buffer.from(
  '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 A legacy document.\\par}',
  'utf8',
);

/**
 * Big enough that a conversion takes long enough to interrupt.
 * Measured: ~850ms of soffice startup plus ~0.4ms per paragraph, so this is
 * roughly 2.5s - comfortably longer than the time it takes to notice soffice
 * running and walk away.
 */
const LARGE_DOCX = buildMinimalDocx(
  Array.from(
    { length: 8000 },
    (_, i) =>
      `Paragraph ${i}: the quick brown fox jumps over the lazy dog, again and again, filling the line so pagination is observable across many pages.`,
  ),
);

let server: TestServer;

before(async () => {
  server = await startTestServer();
});

after(async () => {
  await server.close();
});

describe('POST /convert/tables', () => {
  /** Read one part back out of the workbook the server sent. */
  function workbookPart(body: Buffer, name: string): string {
    const part = readZipEntry(body, name, 4 * 1024 * 1024);
    assert.equal(part.kind, 'found', `${name} is missing from the workbook`);
    return part.kind === 'found' ? part.data.toString('utf8') : '';
  }

  it('extracts a Word table into a workbook', async () => {
    const response = await upload(server.baseUrl, 'report.docx', tablesProbe(), { target: 'tables' });

    assert.equal(response.status, 200);
    // Exactly the spreadsheet media type, with no charset suffix - a client
    // that inspects this header refuses anything that does not match.
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );

    // The workbook is a real one, and the text that was in the document is in
    // it. Reading the parts back with our own reader also proves the package
    // is structurally sound, not merely the right size.
    assert.match(workbookPart(response.body, 'xl/workbook.xml'), /name="Table_1"/);
    const sheet = workbookPart(response.body, 'xl/worksheets/sheet1.xml');
    for (const value of ['Header', 'Value', 'alpha', 'beta', '1', '2']) {
      assert.ok(sheet.includes(value), `"${value}" did not survive the extraction`);
    }
  });

  it('names the download after the upload, with the workbook extension', async () => {
    const response = await upload(server.baseUrl, 'Quarterly report.docx', tablesProbe(), {
      target: 'tables',
    });
    assert.equal(response.status, 200);
    assert.match(response.contentDisposition ?? '', /filename="Quarterly report\.xlsx"/);
  });

  it('answers with the workbook itself, not an archive around it', async () => {
    // `multiple: false` in GET /formats is a promise the client acts on: it
    // reads the body as a workbook rather than unwrapping it. An .xlsx is
    // itself a ZIP, so the check is the media type - wrapping it in another
    // archive would produce a file no client could open.
    const response = await upload(server.baseUrl, 'report.docx', tablesProbe(), { target: 'tables' });
    assert.equal(response.contentType?.includes('application/zip'), false);
    // And the body begins with a local file header: it is the workbook.
    assert.equal(response.body.readUInt32LE(0), 0x04034b50);
  });

  it('refuses a legacy .doc, which is not a package it can read', async () => {
    // `.doc` is the same family as `.docx` and the same audience, but it is a
    // binary container rather than a ZIP of XML parts, so it deliberately does
    // not get the `tables` target. The refusal names what it CAN become.
    const response = await upload(server.baseUrl, 'legacy.doc', SAMPLE_DOCX, { target: 'tables' });
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.match(error.message, /A \.doc file can be converted to: /);
    assert.equal(/tables/i.test(error.message), false, 'the .doc list must not offer tables');
  });

  it('deletes the workspace after an extraction', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'report.docx', tablesProbe(), { target: 'tables' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/layers', () => {
  /** Every entry name in the archive the server sent. */
  function entryNames(body: Buffer): string[] {
    const names: string[] = [];
    let at = 0;
    while (at < body.length - 4) {
      const next = body.indexOf(Buffer.from('PK\u0001\u0002', 'latin1'), at);
      if (next < 0) break;
      const nameLength = body.readUInt16LE(next + 28);
      names.push(body.toString('utf8', next + 46, next + 46 + nameLength));
      at = next + 46 + nameLength;
    }
    return names;
  }

  function entry(body: Buffer, name: string): Buffer {
    const part = readZipEntry(body, name, 8 * 1024 * 1024);
    assert.equal(part.kind, 'found', `${name} is missing from the archive`);
    return part.kind === 'found' ? part.data : Buffer.alloc(0);
  }

  it('returns one PNG per layer, in its group, with a manifest', async () => {
    const response = await upload(server.baseUrl, 'design.psd', psdProbe(), { target: 'layers' });

    assert.equal(response.status, 200);
    // Always an archive, whatever the document held - the same promise the
    // image targets make, and for the same reason.
    assert.equal(response.contentType, 'application/zip');
    assert.match(response.contentDisposition ?? '', /\.zip"|\?UTF-8''.*\.zip/);
    assert.ok(response.body.subarray(0, 2).equals(Buffer.from('PK', 'latin1')), 'not a ZIP');

    // The probe is two drawable layers, one of them hidden and one inside a
    // group, plus an empty layer that must not become a file. Asserting the
    // exact set is the whole point: the count is the thing that goes wrong
    // silently, and every file here would still be a valid PNG if it did.
    const names = entryNames(response.body);
    assert.deepEqual(names.sort(), [
      'Background.png',
      'Buttons/Hover.png',
      'Buttons/Normal.png',
      'manifest.json',
    ]);

    // Each image really is a PNG, not merely a file with the right name.
    for (const name of names.filter((entry) => entry.endsWith('.png'))) {
      assert.ok(
        entry(response.body, name)
          .subarray(0, 8)
          .equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])),
        `${name} is not a PNG`,
      );
    }

    const manifest = JSON.parse(entry(response.body, 'manifest.json').toString('utf8')) as {
      canvas: { width: number; height: number };
      exported: number;
      skipped: number;
      layers: Array<{ name: string; file: string | null; hidden: boolean }>;
    };
    assert.deepEqual(manifest.canvas, { width: 16, height: 16 });
    assert.equal(manifest.exported, 3);
    assert.equal(manifest.skipped, 1, 'the empty layer must be recorded, not dropped');
    // The manifest describes the skipped layer by name and gives it no file,
    // so a client can say what was in the document rather than guessing.
    assert.equal(manifest.layers.find((record) => record.name === 'Levels')?.file, null);
    assert.equal(manifest.layers.find((record) => record.name === 'Hover')?.hidden, true);
  });

  it('refuses a document that is not a PSD', async () => {
    // The extension is the only thing trusted, so a renamed file is a routine
    // input rather than an exotic one - and it must read as "we could not read
    // this" rather than as a server fault.
    const response = await upload(server.baseUrl, 'fake.psd', Buffer.from('not a photoshop file'), {
      target: 'layers',
    });
    expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
  });

  it('offers layers only from a PSD, and a PSD only layers', async () => {
    const fromDocx = await upload(server.baseUrl, 'ok.docx', SAMPLE_DOCX, { target: 'layers' });
    const error = expectJsonEnvelope(fromDocx, 415, 'E_UNSUPPORTED_TARGET');
    assert.equal(/PNG \(layers\)/.test(error.message), false, 'a .docx cannot become layers');

    const fromPsd = await upload(server.baseUrl, 'design.psd', psdProbe(), { target: 'pdf' });
    const psdError = expectJsonEnvelope(fromPsd, 415, 'E_UNSUPPORTED_TARGET');
    assert.match(psdError.message, /A \.psd file can be converted to: PNG \(layers\)\./);
  });

  it('deletes the workspace after an extraction', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'design.psd', psdProbe(), { target: 'layers' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});
