/**
 * End-to-end tests against the real HTTP surface, converting real documents
 * with the real soffice.
 *
 * These assert the wire contract the shipped Android client depends on: a
 * success is application/pdf, a failure is a non-2xx carrying the JSON
 * envelope, and a failure is never a 200.
 */
import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fsp from 'node:fs/promises';
import { promisify } from 'node:util';

import {
  buildPptxFixture,
  expectJsonEnvelope,
  listWorkspaces,
  startTestServer,
  upload,
  waitFor,
  zipEntryNames,
  type TestServer,
} from './helpers.ts';
import {
  buildEncryptedDocxContainer,
  buildEncryptedLegacyDoc,
  buildEncryptedPdfContainer,
  buildMalformedDocx,
} from './fixtures.ts';

const execFileAsync = promisify(execFile);

const {
  buildMinimalDocx,
  buildMinimalOdp,
  buildSolidPng,
  pdfProbe,
  pdfWithType3FontProbe,
  pdfTableProbe,
  psdProbe,
  tablesProbe,
} = await import('../src/lib/probe-documents.ts');
const { readZipEntry } = await import('../src/lib/unzip.ts');
const { MAX_UPLOAD_BYTES } = await import('../src/config.ts');

/** A small but genuine .docx, built from real OOXML parts. */
const SAMPLE_DOCX = buildMinimalDocx([
  'Pagination fidelity check',
  'Calibri and Cambria metrics determine where every line breaks.',
  'The quick brown fox jumps over the lazy dog, repeatedly, to fill a line.',
]);

/**
 * The non-Word sources used by the matrix tests.
 *
 * These are written as literal file contents rather than built, because that is
 * what they are: CSV, text and RTF have no container to construct, and a
 * fixture that looks like the file a user would upload is easier to trust than
 * one that is generated by code nobody reads.
 */
const SAMPLE_CSV = Buffer.from('name,qty,price\nwidget,3,9.99\ngadget,12,1.5\n', 'utf8');
const SAMPLE_TXT = Buffer.from('A plain text note.\nSecond line.\n', 'utf8');
const SAMPLE_RTF = Buffer.from(
  '{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 A legacy document.\\par}',
  'utf8',
);

/**
 * Big enough that a conversion takes long enough to interrupt.
 * Measured: ~850ms of soffice startup plus ~0.4ms per paragraph, so this is
 * roughly 2.5s - comfortably longer than the time it takes to notice soffice
 * running and walk away.
 */
const LARGE_DOCX = buildMinimalDocx(
  Array.from(
    { length: 8000 },
    (_, i) =>
      `Paragraph ${i}: the quick brown fox jumps over the lazy dog, again and again, filling the line so pagination is observable across many pages.`,
  ),
);

let server: TestServer;

before(async () => {
  server = await startTestServer();
});

after(async () => {
  await server.close();
});

describe('GET /health', () => {
  it('reports ok once soffice has been confirmed', async () => {
    const response = await fetch(`${server.baseUrl}/health`);
    assert.equal(response.status, 200);
    assert.match(response.headers.get('content-type') ?? '', /application\/json/);
    assert.deepEqual(await response.json(), { status: 'ok' });
  });
});

describe('POST /convert/pdf - success', () => {
  it('converts a real .docx and returns PDF bytes', async () => {
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX);

    assert.equal(response.status, 200);
    // Constraint 1: the client checks this header and refuses anything else.
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
    assert.ok(response.body.length > 1000, 'PDF looks implausibly small');
  });

  it('accepts .docm', async () => {
    const response = await upload(server.baseUrl, 'sample.docm', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('accepts a .doc extension', async () => {
    // LibreOffice sniffs content, so OOXML written under a .doc name still
    // converts - the point here is that the extension is allowed through the
    // filter rather than rejected with 415.
    const response = await upload(server.baseUrl, 'sample.doc', SAMPLE_DOCX);
    assert.notEqual(response.status, 415);
  });

  it('picks the import filter from the filename, not the declared MIME type', async () => {
    // The client deliberately sends application/octet-stream; a hostile client
    // could send anything at all. The extension is the only thing we act on.
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, {
      mimeType: 'image/png',
    });
    assert.equal(response.status, 200);
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('ignores a path-traversal filename and keeps the upload inside its workspace', async () => {
    const response = await upload(server.baseUrl, '../../../../tmp/evil.docx', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    // Nothing was written outside the temp root: the name on disk is ours.
    assert.equal(await fsp.readdir('/tmp').then((e) => e.includes('evil.docx')), false);
  });

  it('deletes the workspace before answering', async () => {
    const before_ = await listWorkspaces();
    const response = await upload(server.baseUrl, 'cleanup.docx', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    // Cleanup happens before the response is written, so there is no race here.
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/pdf - rejections', () => {
  it('rejects an oversized upload with 413', async () => {
    const response = await upload(
      server.baseUrl,
      'big.docx',
      Buffer.alloc(MAX_UPLOAD_BYTES + 1024, 0x41),
    );
    // multer's default here would be an HTML error page; the client needs JSON.
    const error = expectJsonEnvelope(response, 413, 'E_TOO_LARGE');
    assert.equal(error.message, 'This document is too large to convert.');
  });

  it('rejects an unsupported extension with 415', async () => {
    // .gif is not in the matrix - and note that .png IS, so this test has to
    // name something genuinely outside it to stay meaningful.
    const response = await upload(server.baseUrl, 'animation.gif', SAMPLE_DOCX);
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED');
    assert.match(error.message, /^This file type cannot be converted\. Supported types: /);
    // The message has to say what WOULD work, not just that this did not.
    assert.match(error.message, /\.docx/);
  });

  it('rejects a file with no extension with 415', async () => {
    const response = await upload(server.baseUrl, 'document', SAMPLE_DOCX);
    expectJsonEnvelope(response, 415, 'E_UNSUPPORTED');
  });

  it('rejects a malformed document with 500', async () => {
    const response = await upload(server.baseUrl, 'broken.docx', buildMalformedDocx());
    const error = expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
    assert.equal(
      error.message,
      'This document could not be converted. It may be damaged or in a format the converter does not support.',
    );
  });

  it('rejects an empty upload rather than returning a blank PDF', async () => {
    // LibreOffice happily opens a zero-byte file as an empty document and
    // exports a valid blank PDF, which would be a 200 carrying a document the
    // user never had.
    const response = await upload(server.baseUrl, 'empty.docx', Buffer.alloc(0));
    expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
  });

  it('rejects an encrypted .docx with 422', async () => {
    const response = await upload(server.baseUrl, 'secret.docx', buildEncryptedDocxContainer());
    const error = expectJsonEnvelope(response, 422, 'E_ENCRYPTED');
    assert.equal(error.message, 'This document is password protected.');
  });

  it('rejects an encrypted legacy .doc with 422', async () => {
    const response = await upload(server.baseUrl, 'secret.doc', buildEncryptedLegacyDoc());
    expectJsonEnvelope(response, 422, 'E_ENCRYPTED');
  });

  it('rejects a request with no file part with 400', async () => {
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, {
      fieldName: 'document',
    });
    expectJsonEnvelope(response, 400, 'E_BAD_REQUEST');
  });

  it('never returns a failure as a 200', async () => {
    const failures = [
      await upload(server.baseUrl, 'animation.gif', SAMPLE_DOCX),
      await upload(server.baseUrl, 'broken.docx', buildMalformedDocx()),
      await upload(server.baseUrl, 'empty.docx', Buffer.alloc(0)),
      await upload(server.baseUrl, 'secret.docx', buildEncryptedDocxContainer()),
    ];
    for (const response of failures) {
      assert.notEqual(response.status, 200);
      assert.ok(response.status >= 400 && response.status < 600);
      assert.match(response.contentType ?? '', /application\/json/);
    }
  });

  it('deletes the workspace after a failed conversion', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'broken.docx', buildMalformedDocx());
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('the target segment is required', () => {
  it('does not serve the bare /convert path', async () => {
    // The alias was removed deliberately. A request to it now lands on the
    // catch-all 404, whose message happens to be the right thing to say to
    // someone on an out-of-date client: "please update the app".
    const form = new FormData();
    form.append('file', new Blob([SAMPLE_DOCX]), 'sample.docx');
    const response = await fetch(`${server.baseUrl}/convert`, { method: 'POST', body: form });

    assert.equal(response.status, 404);
    const body = (await response.json()) as { error: { code: string; message: string } };
    assert.equal(body.error.code, 'E_BAD_REQUEST');
    assert.equal(
      body.error.message,
      'The converter is not available at this address. Please update the app and try again.',
    );
  });

  it('serves the same conversion at /convert/pdf', async () => {
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, { target: 'pdf' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });
});

describe('download filenames', () => {
  it('keeps the upload name and swaps the extension', async () => {
    const response = await upload(server.baseUrl, 'Quarterly report.docx', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    assert.match(response.contentDisposition ?? '', /filename="Quarterly report\.pdf"/);
  });

  it('names a raster archive after the deck it came from', async () => {
    // The ENTRIES stay slide-1.png, slide-2.png; only the archive is named
    // after the upload, so unzipping gives predictable page names either way.
    const response = await upload(server.baseUrl, 'my deck.odp', buildMinimalOdp(['a', 'b']), {
      target: 'png',
    });
    assert.equal(response.status, 200);
    assert.match(response.contentDisposition ?? '', /filename="my deck\.zip"/);
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.png', 'slide-2.png']);
  });

  it('keeps a non-ASCII name intact through the whole stack', async () => {
    // The end-to-end version of the decode test: this goes through the real
    // multipart parser, so if multer's treatment of the filename ever changes
    // (or is fixed upstream), the unit test still passes while this one does
    // not - which is the one that describes what a user experiences.
    const name = 'KVADRAT KÖKLƏR 8-Cİ SİNİF (ARZU ƏLƏDDİN QIZI 051-641-88-34)';
    const response = await upload(server.baseUrl, `${name}.docx`, SAMPLE_DOCX);

    assert.equal(response.status, 200);
    const disposition = response.contentDisposition ?? '';

    // The starred form is what current clients read, and it must carry the
    // exact name the user typed. Compared as a substring rather than matched as
    // a pattern: the name contains parentheses, which `encodeURIComponent`
    // leaves alone and a regex would read as grouping.
    const expected = `filename*=UTF-8''${encodeURIComponent(name)}.pdf`;
    assert.ok(
      disposition.includes(expected),
      `expected the header to carry ${expected}, got ${disposition}`,
    );
    // And nothing left over from the latin1 misreading: no C1 controls, and
    // no `Ã`/`Ä` pile-up.
    assert.doesNotMatch(disposition, /[\u0080-\u009f]/, 'a C1 control reached the header');
    assert.doesNotMatch(disposition, /Ã|Ä|Æ/, 'the latin1 misreading was passed on');
  });

  it('does not let a hostile filename reach the header', async () => {
    // The name is attacker-controlled and this value is a response header, so
    // a CRLF in it would be a header injection. Sanitised, not escaped.
    const response = await upload(server.baseUrl, '../../etc/evil\r\nX-Loop: 1.docx', SAMPLE_DOCX);
    assert.equal(response.status, 200);
    const disposition = response.contentDisposition ?? '';
    assert.doesNotMatch(disposition, /[\r\n]/, 'a newline reached the header');
    assert.match(disposition, /filename="evilX-Loop: 1\.pdf"/);
  });
});

describe('POST /convert/<target> - the universal matrix', () => {
  it('converts a CSV to a real XLSX', async () => {
    const response = await upload(server.baseUrl, 'sheet.csv', SAMPLE_CSV, { target: 'xlsx' });

    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );
    // An xlsx is a ZIP package.
    assert.equal(response.body.readUInt32LE(0), 0x04034b50);
  });

  it('converts a CSV to PDF', async () => {
    const response = await upload(server.baseUrl, 'sheet.csv', SAMPLE_CSV, { target: 'pdf' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('converts a plain text file to DOCX', async () => {
    const response = await upload(server.baseUrl, 'notes.txt', SAMPLE_TXT, { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'docx is not a zip package');
  });

  it('converts an RTF to ODT', async () => {
    const response = await upload(server.baseUrl, 'legacy.rtf', SAMPLE_RTF, { target: 'odt' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/vnd.oasis.opendocument.text');
  });

  it('converts an image to PDF', async () => {
    const response = await upload(server.baseUrl, 'photo.png', buildSolidPng(16, 16, [10, 90, 200]));
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.equal(response.body.subarray(0, 5).toString('latin1'), '%PDF-');
  });

  it('converts a Word document to plain text and EPUB', async () => {
    const text = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, { target: 'txt' });
    assert.equal(text.status, 200);
    assert.match(text.contentType ?? '', /^text\/plain/);
    assert.match(text.body.toString('utf8'), /Pagination fidelity check/);

    const epub = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, { target: 'epub' });
    assert.equal(epub.status, 200);
    assert.equal(epub.contentType, 'application/epub+zip');
    assert.equal(epub.body.readUInt32LE(0), 0x04034b50, 'epub is not a zip package');
  });

  it('converts a two-slide deck to one PNG per slide, as an archive', async () => {
    // The whole reason the raster pipeline exists: LibreOffice's own image
    // export writes only the first slide, so if this ever returns a single
    // image the two-step path has been broken or bypassed.
    const response = await upload(server.baseUrl, 'deck.pptx', await buildPptxFixture(['one', 'two']), {
      target: 'png',
    });

    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.png', 'slide-2.png']);
  });

  it('rasterises a LibreOffice-native deck too', async () => {
    // .odp and .pptx are the same kind of document, so the image targets are
    // offered from both. This uses the hand-built ODP rather than the generated
    // PPTX, so it exercises the raster pipeline with no fixture dependency at
    // all - if the two ever diverge, the absence of a gap here is the point.
    const response = await upload(server.baseUrl, 'deck.odp', buildMinimalOdp(['one', 'two']), {
      target: 'png',
    });

    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.png', 'slide-2.png']);
  });

  it('converts a deck to ODP', async () => {
    const response = await upload(server.baseUrl, 'deck.pptx', await buildPptxFixture(['one']), {
      target: 'odp',
    });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/vnd.oasis.opendocument.presentation');
  });

  it('answers JPG requests with an archive too, whatever the page count', async () => {
    // A single-slide deck still answers with a zip: the content type must not
    // depend on how many slides the upload happened to have, or every client
    // has to sniff what it received.
    const response = await upload(server.baseUrl, 'one.pptx', await buildPptxFixture(['only']), {
      target: 'jpg',
    });

    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body), ['slide-1.jpg']);
  });

  it('rejects a target the source cannot become, listing what it can', async () => {
    // A .docx is a document; there is no sensible way to make it a slide deck.
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, { target: 'png' });

    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.equal(
      error.message,
      'A .docx file can be converted to: PDF, ODT, TXT, HTML, RTF, EPUB, XLSX (tables).',
    );
  });

  it('rejects an unknown target with 404, without reading the upload', async () => {
    const response = await upload(server.baseUrl, 'sample.docx', SAMPLE_DOCX, {
      target: 'banana',
    });

    const error = expectJsonEnvelope(response, 404, 'E_UNKNOWN_TARGET');
    // It has to name the real options - this is the only place a client can
    // discover them from an error.
    assert.match(error.message, /PDF/);
    assert.match(error.message, /XLSX/);
  });

  it('deletes the workspace after a matrix conversion', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'sheet.csv', SAMPLE_CSV, { target: 'xlsx' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/tables', () => {
  /** Read one part back out of the workbook the server sent. */
  function workbookPart(body: Buffer, name: string): string {
    const part = readZipEntry(body, name, 4 * 1024 * 1024);
    assert.equal(part.kind, 'found', `${name} is missing from the workbook`);
    return part.kind === 'found' ? part.data.toString('utf8') : '';
  }

  it('extracts a Word table into a workbook', async () => {
    const response = await upload(server.baseUrl, 'report.docx', tablesProbe(), { target: 'tables' });

    assert.equal(response.status, 200);
    // Exactly the spreadsheet media type, with no charset suffix - a client
    // that inspects this header refuses anything that does not match.
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );

    // The workbook is a real one, and the text that was in the document is in
    // it. Reading the parts back with our own reader also proves the package
    // is structurally sound, not merely the right size.
    assert.match(workbookPart(response.body, 'xl/workbook.xml'), /name="Table_1"/);
    const sheet = workbookPart(response.body, 'xl/worksheets/sheet1.xml');
    for (const value of ['Header', 'Value', 'alpha', 'beta', '1', '2']) {
      assert.ok(sheet.includes(value), `"${value}" did not survive the extraction`);
    }
  });

  it('names the download after the upload, with the workbook extension', async () => {
    const response = await upload(server.baseUrl, 'Quarterly report.docx', tablesProbe(), {
      target: 'tables',
    });
    assert.equal(response.status, 200);
    assert.match(response.contentDisposition ?? '', /filename="Quarterly report\.xlsx"/);
  });

  it('answers with the workbook itself, not an archive around it', async () => {
    // `multiple: false` in GET /formats is a promise the client acts on: it
    // reads the body as a workbook rather than unwrapping it. An .xlsx is
    // itself a ZIP, so the check is the media type - wrapping it in another
    // archive would produce a file no client could open.
    const response = await upload(server.baseUrl, 'report.docx', tablesProbe(), { target: 'tables' });
    assert.equal(response.contentType?.includes('application/zip'), false);
    // And the body begins with a local file header: it is the workbook.
    assert.equal(response.body.readUInt32LE(0), 0x04034b50);
  });

  it('refuses a legacy .doc, which is not a package it can read', async () => {
    // `.doc` is the same family as `.docx` and the same audience, but it is a
    // binary container rather than a ZIP of XML parts, so it deliberately does
    // not get the `tables` target. The refusal names what it CAN become.
    const response = await upload(server.baseUrl, 'legacy.doc', SAMPLE_DOCX, { target: 'tables' });
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.match(error.message, /A \.doc file can be converted to: /);
    assert.equal(/tables/i.test(error.message), false, 'the .doc list must not offer tables');
  });

  it('deletes the workspace after an extraction', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'report.docx', tablesProbe(), { target: 'tables' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/layers', () => {
  /** Every entry name in the archive the server sent. */
  function entryNames(body: Buffer): string[] {
    const names: string[] = [];
    let at = 0;
    while (at < body.length - 4) {
      const next = body.indexOf(Buffer.from('PK\u0001\u0002', 'latin1'), at);
      if (next < 0) break;
      const nameLength = body.readUInt16LE(next + 28);
      names.push(body.toString('utf8', next + 46, next + 46 + nameLength));
      at = next + 46 + nameLength;
    }
    return names;
  }

  function entry(body: Buffer, name: string): Buffer {
    const part = readZipEntry(body, name, 8 * 1024 * 1024);
    assert.equal(part.kind, 'found', `${name} is missing from the archive`);
    return part.kind === 'found' ? part.data : Buffer.alloc(0);
  }

  it('returns one PNG per layer, in its group, with a manifest', async () => {
    const response = await upload(server.baseUrl, 'design.psd', psdProbe(), { target: 'layers' });

    assert.equal(response.status, 200);
    // Always an archive, whatever the document held - the same promise the
    // image targets make, and for the same reason.
    assert.equal(response.contentType, 'application/zip');
    assert.match(response.contentDisposition ?? '', /\.zip"|\?UTF-8''.*\.zip/);
    assert.ok(response.body.subarray(0, 2).equals(Buffer.from('PK', 'latin1')), 'not a ZIP');

    // The probe is two drawable layers, one of them hidden and one inside a
    // group, plus an empty layer that must not become a file. Asserting the
    // exact set is the whole point: the count is the thing that goes wrong
    // silently, and every file here would still be a valid PNG if it did.
    const names = entryNames(response.body);
    assert.deepEqual(names.sort(), [
      'Background.png',
      'Buttons/Hover.png',
      'Buttons/Normal.png',
      'manifest.json',
    ]);

    // Each image really is a PNG, not merely a file with the right name.
    for (const name of names.filter((entry) => entry.endsWith('.png'))) {
      assert.ok(
        entry(response.body, name)
          .subarray(0, 8)
          .equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])),
        `${name} is not a PNG`,
      );
    }

    const manifest = JSON.parse(entry(response.body, 'manifest.json').toString('utf8')) as {
      canvas: { width: number; height: number };
      exported: number;
      skipped: number;
      layers: Array<{ name: string; file: string | null; hidden: boolean }>;
    };
    assert.deepEqual(manifest.canvas, { width: 16, height: 16 });
    assert.equal(manifest.exported, 3);
    assert.equal(manifest.skipped, 1, 'the empty layer must be recorded, not dropped');
    // The manifest describes the skipped layer by name and gives it no file,
    // so a client can say what was in the document rather than guessing.
    assert.equal(manifest.layers.find((record) => record.name === 'Levels')?.file, null);
    assert.equal(manifest.layers.find((record) => record.name === 'Hover')?.hidden, true);
  });

  it('refuses a document that is not a PSD', async () => {
    // The extension is the only thing trusted, so a renamed file is a routine
    // input rather than an exotic one - and it must read as "we could not read
    // this" rather than as a server fault.
    const response = await upload(server.baseUrl, 'fake.psd', Buffer.from('not a photoshop file'), {
      target: 'layers',
    });
    expectJsonEnvelope(response, 500, 'E_CONVERT_FAILED');
  });

  it('offers layers only from a PSD, and a PSD only layers', async () => {
    const fromDocx = await upload(server.baseUrl, 'ok.docx', SAMPLE_DOCX, { target: 'layers' });
    const error = expectJsonEnvelope(fromDocx, 415, 'E_UNSUPPORTED_TARGET');
    assert.equal(/PNG \(layers\)/.test(error.message), false, 'a .docx cannot become layers');

    const fromPsd = await upload(server.baseUrl, 'design.psd', psdProbe(), { target: 'pdf' });
    const psdError = expectJsonEnvelope(fromPsd, 415, 'E_UNSUPPORTED_TARGET');
    assert.match(psdError.message, /A \.psd file can be converted to: PNG \(layers\)\./);
  });

  it('deletes the workspace after an extraction', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'design.psd', psdProbe(), { target: 'layers' });
    assert.deepEqual(await listWorkspaces(), before_);
  });
});

describe('POST /convert/<target> - PDF sources', () => {
  /**
   * `pdfa`/`png`/`jpg` are direct/raster LibreOffice targets - a PDF is
   * always opened as a Draw document, and these are Draw's own export
   * filters. `docx`/`pptx`/`xlsx` reach no LibreOffice filter at all from a
   * PDF - confirmed by actually running `soffice --convert-to docx/pptx/xlsx`
   * against a real PDF and watching every one fail with "no export filter
   * found" - so a PDF reaches those same three ids through `pdf_engine.py`
   * instead (`engineFrom` in formats.ts). The id is the same one a `.doc`
   * upload reaches through soffice; only the engine behind it differs.
   */
  const TWO_PAGE_PDF = pdfProbe();

  it('re-exports as PDF/A through Draw', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'pdfa' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/pdf');
    assert.ok(response.body.subarray(0, 5).equals(Buffer.from('%PDF-', 'latin1')));
    // PDF/A-1b declares its conformance in the XMP metadata soffice embeds.
    assert.ok(response.body.includes(Buffer.from('pdfaid')), 'not tagged as PDF/A');
  });

  it('rasterises every page, skipping the render-to-PDF step', async () => {
    // The probe has two pages, which is the point: one image each proves the
    // source was rasterised directly rather than silently dropped to one
    // page the way LibreOffice's own image export would.
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'png' });
    assert.equal(response.status, 200);
    assert.equal(response.contentType, 'application/zip');
    assert.deepEqual(zipEntryNames(response.body).sort(), ['slide-1.png', 'slide-2.png']);
  });

  it('reconstructs an editable DOCX with pdf_engine.py', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'not a ZIP-based package');
    const document = readZipEntry(response.body, 'word/document.xml', 4 * 1024 * 1024);
    assert.equal(document.kind, 'found');
    const xml = document.kind === 'found' ? document.data.toString('utf8') : '';
    for (const text of ['Converter warm-up', 'Second page']) {
      assert.ok(xml.includes(text), `"${text}" did not survive the reconstruction`);
    }
  });

  it('falls back to a full-page image for a Type3-font PDF, instead of a corrupted reconstruction', async () => {
    // Regression test for a real failure: pdf2docx duplicated and overlapped
    // every line of a Type3-font PDF (confirmed against the actual file that
    // exposed this), and no pdf2docx setting changed that - so
    // pdf_engine.py detects the trigger and answers with a full-page image
    // instead. This is the one DOCX case where a page IMAGE, not
    // reconstructed text, is the correct and expected output.
    const response = await upload(server.baseUrl, 'doc.pdf', pdfWithType3FontProbe(), { target: 'docx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'not a ZIP-based package');
    assert.deepEqual(
      zipEntryNames(response.body).filter((name) => /^word\/media\//.test(name)),
      ['word/media/image1.png'],
      'expected exactly one full-page image, not a reconstructed text layout',
    );
  });

  it('builds one slide per page, each a full-page image', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'pptx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    );
    assert.equal(response.body.readUInt32LE(0), 0x04034b50, 'not a ZIP-based package');
    assert.deepEqual(
      zipEntryNames(response.body)
        .filter((name) => /^ppt\/slides\/slide\d+\.xml$/.test(name))
        .sort(),
      ['ppt/slides/slide1.xml', 'ppt/slides/slide2.xml'],
    );
  });

  it('extracts a ruled table into a workbook', async () => {
    const response = await upload(server.baseUrl, 'doc.pdf', pdfTableProbe(), { target: 'xlsx' });
    assert.equal(response.status, 200);
    assert.equal(
      response.contentType,
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );
    const sheet = readZipEntry(response.body, 'xl/worksheets/sheet1.xml', 1024 * 1024);
    assert.equal(sheet.kind, 'found');
    const xml = sheet.kind === 'found' ? sheet.data.toString('utf8') : '';
    for (const value of ['A1', 'B1', 'A2', 'B2']) {
      assert.ok(xml.includes(value), `"${value}" did not survive the table extraction`);
    }
  });

  it('answers E_NO_TABLES for a PDF with no ruled table', async () => {
    // The PDF-source twin of the same case for a Word document: the document
    // opened and was read successfully, and simply has nothing to extract.
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'xlsx' });
    const error = expectJsonEnvelope(response, 422, 'E_NO_TABLES');
    assert.equal(error.message, 'This document does not contain any tables.');
  });

  it('offers the same docx/pptx/xlsx ids a .doc upload would, not lookalikes', async () => {
    // There is no separate "from PDF" id to fall out of step with: a PDF
    // lists exactly `docx`/`pptx`/`xlsx` among the formats it can become,
    // the same ids GET /formats advertises for every other source.
    const response = await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'odt' });
    const error = expectJsonEnvelope(response, 415, 'E_UNSUPPORTED_TARGET');
    assert.match(error.message, /A \.pdf file can be converted to: PDF\/A, PNG, JPG, DOCX, PPTX, XLSX\./);
  });

  it('names the download after the upload, with the target extension', async () => {
    const response = await upload(server.baseUrl, 'Contract.pdf', TWO_PAGE_PDF, { target: 'docx' });
    assert.equal(response.status, 200);
    assert.match(response.contentDisposition ?? '', /filename="Contract\.docx"/);
  });

  it('deletes the workspace after a PDF-engine conversion', async () => {
    const before_ = await listWorkspaces();
    await upload(server.baseUrl, 'doc.pdf', TWO_PAGE_PDF, { target: 'docx' });
    assert.deepEqual(await listWorkspaces(), before_);
  });

  it('rejects an encrypted PDF with 422 rather than a generic failure', async () => {
    // Without the PDF branch in isPasswordProtected, this would reach
    // pdf_engine.py (or soffice, for pdfa/png/jpg) and come back as
    // E_CONVERT_FAILED - technically true but the wrong explanation, exactly
    // the failure this check exists to avoid for OOXML and legacy Word.
    const response = await upload(server.baseUrl, 'secret.pdf', buildEncryptedPdfContainer(), {
      target: 'docx',
    });
    const error = expectJsonEnvelope(response, 422, 'E_ENCRYPTED');
    assert.equal(error.message, 'This document is password protected.');
  });
});

describe('GET /formats', () => {
  it('describes the matrix the server actually implements', async () => {
    const response = await fetch(`${server.baseUrl}/formats`);
    assert.equal(response.status, 200);

    const body = (await response.json()) as {
      targets: Array<{ id: string; mediaType: string; multiple: boolean }>;
      sources: Array<{ extension: string; family: string; targets: string[] }>;
    };

    const targetIds = body.targets.map((target) => target.id);
    assert.ok(targetIds.includes('pdf'));
    assert.ok(targetIds.includes('png'));

    // The targets whose answer is an archive. The raster ones are one image per
    // page; `layers` is one image per layer of a PSD. Both are always archives,
    // so this is a fact about the target and not about the document.
    const MULTIPLE = ['png', 'jpg', 'layers'];
    for (const target of body.targets) {
      assert.equal(target.multiple, MULTIPLE.includes(target.id), target.id);
    }

    const docx = body.sources.find((source) => source.extension === '.docx');
    // `tables` is the one Word target LibreOffice does not produce: it is our
    // own extractor reading the document's own package.
    assert.deepEqual(docx?.targets, ['pdf', 'odt', 'txt', 'html', 'rtf', 'epub', 'tables']);

    // Every target a source claims has to exist in the target list, or the
    // document is advertising something the server would 404 on.
    for (const source of body.sources) {
      assert.equal(source.extension, source.extension.toLowerCase());
      for (const target of source.targets) {
        assert.ok(targetIds.includes(target), `${source.extension} claims unknown ${target}`);
      }
    }
  });
});

describe('cancellation', () => {
  it('kills the running soffice when the client disconnects', async () => {
    const controller = new AbortController();
    const form = new FormData();
    form.append('file', new Blob([LARGE_DOCX]), 'large.docx');

    const request = fetch(`${server.baseUrl}/convert/pdf`, {
      method: 'POST',
      body: form,
      signal: controller.signal,
    }).catch(() => undefined); // The abort rejects this; that is the point.

    // Wait for soffice to actually be running, so this test cannot pass
    // vacuously by aborting before any work started.
    const started = await waitFor(async () => (await sofficeForWorkspaces()).length > 0, 30_000);
    assert.ok(started, 'soffice never started; the fixture may be too small to interrupt');

    const abortedAt = Date.now();
    controller.abort();
    await request;

    // The workspace goes away...
    const cleaned = await waitFor(async () => (await listWorkspaces()).length === 0, 20_000);
    assert.ok(cleaned, 'workspace was not cleaned up after the client disconnected');

    // ...and so does the process, rather than burning CPU until the timeout.
    const killed = await waitFor(async () => (await sofficeForWorkspaces()).length === 0, 20_000);
    assert.ok(killed, `soffice still running: ${(await sofficeForWorkspaces()).join(' | ')}`);

    // Proving it was killed rather than merely finishing: an 8000-paragraph
    // document needs ~2.5s, and we walked away about 100ms in. If this were
    // natural completion it could not possibly be this quick.
    const killedAfterMs = Date.now() - abortedAt;
    assert.ok(
      killedAfterMs < 1500,
      `soffice took ${killedAfterMs}ms to disappear after the abort - it looks like it ran to completion instead of being killed`,
    );
  });
});

async function sofficeForWorkspaces(): Promise<string[]> {
  const { TEMP_ROOT } = await import('./helpers.ts');
  try {
    const { stdout } = await execFileAsync('ps', ['-eo', 'args'], { maxBuffer: 8 * 1024 * 1024 });
    return stdout
      .split('\n')
      .filter((line) => line.includes(TEMP_ROOT) && line.includes('soffice'))
      .map((line) => line.trim());
  } catch {
    return [];
  }
}
